# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.schedule_create_payload_v2 import ScheduleCreatePayloadV2
from ..types.schedule_update_payload_v2 import ScheduleUpdatePayloadV2
from ..types.schedules_create_override_result_v2 import SchedulesCreateOverrideResultV2
from ..types.schedules_create_result_v2 import SchedulesCreateResultV2
from ..types.schedules_list_result_v2 import SchedulesListResultV2
from ..types.schedules_list_schedule_entries_result_v2 import SchedulesListScheduleEntriesResultV2
from ..types.schedules_show_result_v2 import SchedulesShowResultV2
from ..types.schedules_update_result_v2 import SchedulesUpdateResultV2
from ..types.user_reference_payload_v2 import UserReferencePayloadV2

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSchedulesV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def listscheduleentries(
        self,
        *,
        schedule_id: str,
        entry_window_start: typing.Optional[dt.datetime] = None,
        entry_window_end: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchedulesListScheduleEntriesResultV2]:
        """
        Get a list of schedule entries. The endpoint will return all entries that overlap with the given window, if one is provided.

        Parameters
        ----------
        schedule_id : str
            The ID of the schedule to get entries for.

        entry_window_start : typing.Optional[dt.datetime]
            The start of the window to get entries for.

        entry_window_end : typing.Optional[dt.datetime]
            The end of the window to get entries for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesListScheduleEntriesResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/schedule_entries",
            method="GET",
            params={
                "schedule_id": schedule_id,
                "entry_window_start": serialize_datetime(entry_window_start)
                if entry_window_start is not None
                else None,
                "entry_window_end": serialize_datetime(entry_window_end) if entry_window_end is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesListScheduleEntriesResultV2,
                    parse_obj_as(
                        type_=SchedulesListScheduleEntriesResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def createoverride(
        self,
        *,
        end_at: dt.datetime,
        layer_id: str,
        rotation_id: str,
        schedule_id: str,
        start_at: dt.datetime,
        user: UserReferencePayloadV2,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchedulesCreateOverrideResultV2]:
        """
        Create a new schedule override.

        Parameters
        ----------
        end_at : dt.datetime
            End time of the override

        layer_id : str
            The layer this override applies to

        rotation_id : str
            The rotation this override applies to

        schedule_id : str
            The schedule this override applies to

        start_at : dt.datetime
            Start time of the override

        user : UserReferencePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesCreateOverrideResultV2]
            Created response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/schedule_overrides",
            method="POST",
            json={
                "end_at": end_at,
                "layer_id": layer_id,
                "rotation_id": rotation_id,
                "schedule_id": schedule_id,
                "start_at": start_at,
                "user": convert_and_respect_annotation_metadata(
                    object_=user, annotation=UserReferencePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesCreateOverrideResultV2,
                    parse_obj_as(
                        type_=SchedulesCreateOverrideResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SchedulesListResultV2]:
        """
        List configured schedules.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            A schedule's ID. This endpoint will return a list of schedules after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesListResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/schedules",
            method="GET",
            params={
                "page_size": page_size,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesListResultV2,
                    parse_obj_as(
                        type_=SchedulesListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self, *, schedule: ScheduleCreatePayloadV2, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SchedulesCreateResultV2]:
        """
        Create a new schedule.

        Parameters
        ----------
        schedule : ScheduleCreatePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesCreateResultV2]
            Created response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/schedules",
            method="POST",
            json={
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=ScheduleCreatePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesCreateResultV2,
                    parse_obj_as(
                        type_=SchedulesCreateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SchedulesShowResultV2]:
        """
        Get a single schedule.

        Parameters
        ----------
        id : str
            Unique internal ID of the schedule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesShowResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesShowResultV2,
                    parse_obj_as(
                        type_=SchedulesShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self, id: str, *, schedule: ScheduleUpdatePayloadV2, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SchedulesUpdateResultV2]:
        """
        Update a schedule.

        Parameters
        ----------
        id : str
            The schedule ID to update.

        schedule : ScheduleUpdatePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SchedulesUpdateResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=ScheduleUpdatePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesUpdateResultV2,
                    parse_obj_as(
                        type_=SchedulesUpdateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def destroy(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Archives a single schedule.

        Parameters
        ----------
        id : str
            Unique internal ID of the schedule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSchedulesV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def listscheduleentries(
        self,
        *,
        schedule_id: str,
        entry_window_start: typing.Optional[dt.datetime] = None,
        entry_window_end: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchedulesListScheduleEntriesResultV2]:
        """
        Get a list of schedule entries. The endpoint will return all entries that overlap with the given window, if one is provided.

        Parameters
        ----------
        schedule_id : str
            The ID of the schedule to get entries for.

        entry_window_start : typing.Optional[dt.datetime]
            The start of the window to get entries for.

        entry_window_end : typing.Optional[dt.datetime]
            The end of the window to get entries for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesListScheduleEntriesResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/schedule_entries",
            method="GET",
            params={
                "schedule_id": schedule_id,
                "entry_window_start": serialize_datetime(entry_window_start)
                if entry_window_start is not None
                else None,
                "entry_window_end": serialize_datetime(entry_window_end) if entry_window_end is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesListScheduleEntriesResultV2,
                    parse_obj_as(
                        type_=SchedulesListScheduleEntriesResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def createoverride(
        self,
        *,
        end_at: dt.datetime,
        layer_id: str,
        rotation_id: str,
        schedule_id: str,
        start_at: dt.datetime,
        user: UserReferencePayloadV2,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchedulesCreateOverrideResultV2]:
        """
        Create a new schedule override.

        Parameters
        ----------
        end_at : dt.datetime
            End time of the override

        layer_id : str
            The layer this override applies to

        rotation_id : str
            The rotation this override applies to

        schedule_id : str
            The schedule this override applies to

        start_at : dt.datetime
            Start time of the override

        user : UserReferencePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesCreateOverrideResultV2]
            Created response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/schedule_overrides",
            method="POST",
            json={
                "end_at": end_at,
                "layer_id": layer_id,
                "rotation_id": rotation_id,
                "schedule_id": schedule_id,
                "start_at": start_at,
                "user": convert_and_respect_annotation_metadata(
                    object_=user, annotation=UserReferencePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesCreateOverrideResultV2,
                    parse_obj_as(
                        type_=SchedulesCreateOverrideResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SchedulesListResultV2]:
        """
        List configured schedules.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            A schedule's ID. This endpoint will return a list of schedules after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesListResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/schedules",
            method="GET",
            params={
                "page_size": page_size,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesListResultV2,
                    parse_obj_as(
                        type_=SchedulesListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self, *, schedule: ScheduleCreatePayloadV2, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SchedulesCreateResultV2]:
        """
        Create a new schedule.

        Parameters
        ----------
        schedule : ScheduleCreatePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesCreateResultV2]
            Created response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/schedules",
            method="POST",
            json={
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=ScheduleCreatePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesCreateResultV2,
                    parse_obj_as(
                        type_=SchedulesCreateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SchedulesShowResultV2]:
        """
        Get a single schedule.

        Parameters
        ----------
        id : str
            Unique internal ID of the schedule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesShowResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesShowResultV2,
                    parse_obj_as(
                        type_=SchedulesShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self, id: str, *, schedule: ScheduleUpdatePayloadV2, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SchedulesUpdateResultV2]:
        """
        Update a schedule.

        Parameters
        ----------
        id : str
            The schedule ID to update.

        schedule : ScheduleUpdatePayloadV2

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SchedulesUpdateResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=ScheduleUpdatePayloadV2, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SchedulesUpdateResultV2,
                    parse_obj_as(
                        type_=SchedulesUpdateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def destroy(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Archives a single schedule.

        Parameters
        ----------
        id : str
            Unique internal ID of the schedule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/schedules/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
