# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .catalog_create_type_payload_v2categories_item import CatalogCreateTypePayloadV2CategoriesItem
    from .catalog_create_type_payload_v2color import CatalogCreateTypePayloadV2Color
    from .catalog_create_type_payload_v2icon import CatalogCreateTypePayloadV2Icon
    from .catalog_update_type_payload_v2categories_item import CatalogUpdateTypePayloadV2CategoriesItem
    from .catalog_update_type_payload_v2color import CatalogUpdateTypePayloadV2Color
    from .catalog_update_type_payload_v2icon import CatalogUpdateTypePayloadV2Icon
_dynamic_imports: typing.Dict[str, str] = {
    "CatalogCreateTypePayloadV2CategoriesItem": ".catalog_create_type_payload_v2categories_item",
    "CatalogCreateTypePayloadV2Color": ".catalog_create_type_payload_v2color",
    "CatalogCreateTypePayloadV2Icon": ".catalog_create_type_payload_v2icon",
    "CatalogUpdateTypePayloadV2CategoriesItem": ".catalog_update_type_payload_v2categories_item",
    "CatalogUpdateTypePayloadV2Color": ".catalog_update_type_payload_v2color",
    "CatalogUpdateTypePayloadV2Icon": ".catalog_update_type_payload_v2icon",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CatalogCreateTypePayloadV2CategoriesItem",
    "CatalogCreateTypePayloadV2Color",
    "CatalogCreateTypePayloadV2Icon",
    "CatalogUpdateTypePayloadV2CategoriesItem",
    "CatalogUpdateTypePayloadV2Color",
    "CatalogUpdateTypePayloadV2Icon",
]
