# This file was auto-generated by Fern from our API Definition.

import typing

CatalogCreateTypePayloadV2Color = typing.Union[
    typing.Literal["yellow", "green", "blue", "violet", "pink", "cyan", "orange"], typing.Any
]
