# This file was auto-generated by Fern from our API Definition.

import typing

CatalogCreateTypePayloadV2Icon = typing.Union[
    typing.Literal[
        "alert",
        "bolt",
        "box",
        "briefcase",
        "browser",
        "bulb",
        "calendar",
        "clock",
        "cog",
        "components",
        "database",
        "doc",
        "email",
        "escalation-path",
        "files",
        "flag",
        "folder",
        "globe",
        "money",
        "server",
        "severity",
        "status-page",
        "store",
        "star",
        "tag",
        "user",
        "users",
    ],
    typing.Any,
]
