# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .workflows_create_workflow_payload_v2runs_on_incident_modes_item import (
        WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem,
    )
    from .workflows_create_workflow_payload_v2runs_on_incidents import WorkflowsCreateWorkflowPayloadV2RunsOnIncidents
    from .workflows_create_workflow_payload_v2state import WorkflowsCreateWorkflowPayloadV2State
    from .workflows_update_workflow_payload_v2runs_on_incident_modes_item import (
        WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem,
    )
    from .workflows_update_workflow_payload_v2runs_on_incidents import WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents
    from .workflows_update_workflow_payload_v2state import WorkflowsUpdateWorkflowPayloadV2State
_dynamic_imports: typing.Dict[str, str] = {
    "WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem": ".workflows_create_workflow_payload_v2runs_on_incident_modes_item",
    "WorkflowsCreateWorkflowPayloadV2RunsOnIncidents": ".workflows_create_workflow_payload_v2runs_on_incidents",
    "WorkflowsCreateWorkflowPayloadV2State": ".workflows_create_workflow_payload_v2state",
    "WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem": ".workflows_update_workflow_payload_v2runs_on_incident_modes_item",
    "WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents": ".workflows_update_workflow_payload_v2runs_on_incidents",
    "WorkflowsUpdateWorkflowPayloadV2State": ".workflows_update_workflow_payload_v2state",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem",
    "WorkflowsCreateWorkflowPayloadV2RunsOnIncidents",
    "WorkflowsCreateWorkflowPayloadV2State",
    "WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem",
    "WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents",
    "WorkflowsUpdateWorkflowPayloadV2State",
]
