# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem = typing.Union[
    typing.Literal["standard", "test", "retrospective"], typing.Any
]
