# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents = typing.Union[
    typing.Literal["newly_created", "newly_created_and_active"], typing.Any
]
