# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowsCreateWorkflowPayloadV2State = typing.Union[typing.Literal["active", "disabled", "draft", "error"], typing.Any]
