# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.condition_group_payload_v2 import ConditionGroupPayloadV2
from ..types.expression_payload_v2 import ExpressionPayloadV2
from ..types.step_config_payload_v2 import StepConfigPayloadV2
from ..types.workflow_delay_v2 import WorkflowDelayV2
from ..types.workflows_create_workflow_result_v2 import WorkflowsCreateWorkflowResultV2
from ..types.workflows_list_workflows_result_v2 import WorkflowsListWorkflowsResultV2
from ..types.workflows_show_workflow_result_v2 import WorkflowsShowWorkflowResultV2
from ..types.workflows_update_workflow_result_v2 import WorkflowsUpdateWorkflowResultV2
from .raw_client import AsyncRawWorkflowsV2Client, RawWorkflowsV2Client
from .types.workflows_create_workflow_payload_v2runs_on_incident_modes_item import (
    WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem,
)
from .types.workflows_create_workflow_payload_v2runs_on_incidents import WorkflowsCreateWorkflowPayloadV2RunsOnIncidents
from .types.workflows_create_workflow_payload_v2state import WorkflowsCreateWorkflowPayloadV2State
from .types.workflows_update_workflow_payload_v2runs_on_incident_modes_item import (
    WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem,
)
from .types.workflows_update_workflow_payload_v2runs_on_incidents import WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents
from .types.workflows_update_workflow_payload_v2state import WorkflowsUpdateWorkflowPayloadV2State

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkflowsV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkflowsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkflowsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkflowsV2Client
        """
        return self._raw_client

    def listworkflows(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowsListWorkflowsResultV2:
        """
        List all workflows

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsListWorkflowsResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.workflows_v2.listworkflows()
        """
        _response = self._raw_client.listworkflows(request_options=request_options)
        return _response.data

    def createworkflow(
        self,
        *,
        condition_groups: typing.Sequence[ConditionGroupPayloadV2],
        continue_on_step_error: bool,
        expressions: typing.Sequence[ExpressionPayloadV2],
        include_private_incidents: bool,
        name: str,
        once_for: typing.Sequence[str],
        runs_on_incident_modes: typing.Sequence[WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem],
        runs_on_incidents: WorkflowsCreateWorkflowPayloadV2RunsOnIncidents,
        steps: typing.Sequence[StepConfigPayloadV2],
        trigger: str,
        annotations: typing.Optional[typing.Dict[str, str]] = OMIT,
        delay: typing.Optional[WorkflowDelayV2] = OMIT,
        folder: typing.Optional[str] = OMIT,
        include_private_escalations: typing.Optional[bool] = OMIT,
        shortform: typing.Optional[str] = OMIT,
        state: typing.Optional[WorkflowsCreateWorkflowPayloadV2State] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsCreateWorkflowResultV2:
        """
        Create a new workflow

        Parameters
        ----------
        condition_groups : typing.Sequence[ConditionGroupPayloadV2]
            Conditions that apply to the workflow trigger

        continue_on_step_error : bool
            Whether to continue executing the workflow if a step fails

        expressions : typing.Sequence[ExpressionPayloadV2]
            The expressions to use in the workflow

        include_private_incidents : bool
            Whether to include private incidents

        name : str
            Name provided by the user when creating the workflow

        once_for : typing.Sequence[str]
            This workflow will run 'once for' a list of references

        runs_on_incident_modes : typing.Sequence[WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem]
            Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.

        runs_on_incidents : WorkflowsCreateWorkflowPayloadV2RunsOnIncidents
            Which incidents should the workflow be applied to?

        steps : typing.Sequence[StepConfigPayloadV2]
            Steps that are executed as part of the workflow

        trigger : str
            Trigger to set on the workflow

        annotations : typing.Optional[typing.Dict[str, str]]
            Annotations that track metadata about this resource

        delay : typing.Optional[WorkflowDelayV2]

        folder : typing.Optional[str]
            Folder to display the workflow in

        include_private_escalations : typing.Optional[bool]
            Whether to include private escalations

        shortform : typing.Optional[str]
            The shortform used to trigger this workflow (only applicable for manual triggers)

        state : typing.Optional[WorkflowsCreateWorkflowPayloadV2State]
            What state this workflow is in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsCreateWorkflowResultV2
            Created response.

        Examples
        --------
        from fern import (
            ConditionGroupPayloadV2,
            ConditionPayloadV2,
            EngineParamBindingPayloadV2,
            EngineParamBindingValuePayloadV2,
            ExpressionBranchesOptsPayloadV2,
            ExpressionBranchPayloadV2,
            ExpressionConcatenateOptsPayloadV2,
            ExpressionElseBranchPayloadV2,
            ExpressionFilterOptsPayloadV2,
            ExpressionNavigateOptsPayloadV2,
            ExpressionOperationPayloadV2,
            ExpressionParseOptsPayloadV2,
            ExpressionPayloadV2,
            IncidentIO,
            ReturnsMetaV2,
            StepConfigPayloadV2,
            WorkflowDelayV2,
        )

        client = IncidentIO()
        client.workflows_v2.createworkflow(
            annotations={"incident.io/terraform/version": "3.0.0"},
            condition_groups=[
                ConditionGroupPayloadV2(
                    conditions=[
                        ConditionPayloadV2(
                            operation="one_of",
                            param_bindings=[
                                EngineParamBindingPayloadV2(
                                    array_value=[
                                        EngineParamBindingValuePayloadV2(
                                            literal="SEV123",
                                            reference="incident.severity",
                                        )
                                    ],
                                    value=EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    ),
                                )
                            ],
                            subject="incident.severity",
                        )
                    ],
                )
            ],
            continue_on_step_error=True,
            delay=WorkflowDelayV2(
                conditions_apply_over_delay=False,
                for_seconds=60,
            ),
            expressions=[
                ExpressionPayloadV2(
                    else_branch=ExpressionElseBranchPayloadV2(
                        result=EngineParamBindingPayloadV2(
                            array_value=[
                                EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                )
                            ],
                            value=EngineParamBindingValuePayloadV2(
                                literal="SEV123",
                                reference="incident.severity",
                            ),
                        ),
                    ),
                    label="Team Slack channel",
                    operations=[
                        ExpressionOperationPayloadV2(
                            branches=ExpressionBranchesOptsPayloadV2(
                                branches=[
                                    ExpressionBranchPayloadV2(
                                        condition_groups=[
                                            ConditionGroupPayloadV2(
                                                conditions=[
                                                    ConditionPayloadV2(
                                                        operation="one_of",
                                                        param_bindings=[
                                                            EngineParamBindingPayloadV2(
                                                                array_value=[
                                                                    EngineParamBindingValuePayloadV2(
                                                                        literal="SEV123",
                                                                        reference="incident.severity",
                                                                    )
                                                                ],
                                                                value=EngineParamBindingValuePayloadV2(
                                                                    literal="SEV123",
                                                                    reference="incident.severity",
                                                                ),
                                                            )
                                                        ],
                                                        subject="incident.severity",
                                                    )
                                                ],
                                            )
                                        ],
                                        result=EngineParamBindingPayloadV2(
                                            array_value=[
                                                EngineParamBindingValuePayloadV2(
                                                    literal="SEV123",
                                                    reference="incident.severity",
                                                )
                                            ],
                                            value=EngineParamBindingValuePayloadV2(
                                                literal="SEV123",
                                                reference="incident.severity",
                                            ),
                                        ),
                                    )
                                ],
                                returns=ReturnsMetaV2(
                                    array=True,
                                    type="IncidentStatus",
                                ),
                            ),
                            concatenate=ExpressionConcatenateOptsPayloadV2(
                                reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                            ),
                            filter=ExpressionFilterOptsPayloadV2(
                                condition_groups=[
                                    ConditionGroupPayloadV2(
                                        conditions=[
                                            ConditionPayloadV2(
                                                operation="one_of",
                                                param_bindings=[
                                                    EngineParamBindingPayloadV2(
                                                        array_value=[
                                                            EngineParamBindingValuePayloadV2(
                                                                literal="SEV123",
                                                                reference="incident.severity",
                                                            )
                                                        ],
                                                        value=EngineParamBindingValuePayloadV2(
                                                            literal="SEV123",
                                                            reference="incident.severity",
                                                        ),
                                                    )
                                                ],
                                                subject="incident.severity",
                                            )
                                        ],
                                    )
                                ],
                            ),
                            navigate=ExpressionNavigateOptsPayloadV2(
                                reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                            ),
                            operation_type="navigate",
                            parse=ExpressionParseOptsPayloadV2(
                                returns=ReturnsMetaV2(
                                    array=True,
                                    type="IncidentStatus",
                                ),
                                source='metadata.annotations["github.com/repo"]',
                            ),
                        )
                    ],
                    reference="abc123",
                    root_reference="incident.status",
                )
            ],
            folder="My folder 01",
            include_private_escalations=True,
            include_private_incidents=True,
            name="My little workflow",
            once_for=["incident.url"],
            runs_on_incident_modes=["standard", "test", "retrospective"],
            runs_on_incidents="newly_created",
            shortform="page-the-ceo",
            state="active",
            steps=[
                StepConfigPayloadV2(
                    for_each="abc123",
                    id="abc123",
                    name="pagerduty.escalate",
                    param_bindings=[
                        EngineParamBindingPayloadV2(
                            array_value=[
                                EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                )
                            ],
                            value=EngineParamBindingValuePayloadV2(
                                literal="SEV123",
                                reference="incident.severity",
                            ),
                        )
                    ],
                )
            ],
            trigger="incident.updated",
        )
        """
        _response = self._raw_client.createworkflow(
            condition_groups=condition_groups,
            continue_on_step_error=continue_on_step_error,
            expressions=expressions,
            include_private_incidents=include_private_incidents,
            name=name,
            once_for=once_for,
            runs_on_incident_modes=runs_on_incident_modes,
            runs_on_incidents=runs_on_incidents,
            steps=steps,
            trigger=trigger,
            annotations=annotations,
            delay=delay,
            folder=folder,
            include_private_escalations=include_private_escalations,
            shortform=shortform,
            state=state,
            request_options=request_options,
        )
        return _response.data

    def showworkflow(
        self,
        id: str,
        *,
        skip_step_upgrades: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsShowWorkflowResultV2:
        """
        Show a workflow by ID

        Parameters
        ----------
        id : str
            Unique identifier for the workflow

        skip_step_upgrades : typing.Optional[bool]
            Skips workflow step upgrades, when the parameters for an existing workflow step change

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsShowWorkflowResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.workflows_v2.showworkflow(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
            skip_step_upgrades=False,
        )
        """
        _response = self._raw_client.showworkflow(
            id, skip_step_upgrades=skip_step_upgrades, request_options=request_options
        )
        return _response.data

    def updateworkflow(
        self,
        id: str,
        *,
        condition_groups: typing.Sequence[ConditionGroupPayloadV2],
        continue_on_step_error: bool,
        expressions: typing.Sequence[ExpressionPayloadV2],
        include_private_incidents: bool,
        name: str,
        once_for: typing.Sequence[str],
        runs_on_incident_modes: typing.Sequence[WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem],
        runs_on_incidents: WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents,
        steps: typing.Sequence[StepConfigPayloadV2],
        annotations: typing.Optional[typing.Dict[str, str]] = OMIT,
        delay: typing.Optional[WorkflowDelayV2] = OMIT,
        folder: typing.Optional[str] = OMIT,
        include_private_escalations: typing.Optional[bool] = OMIT,
        shortform: typing.Optional[str] = OMIT,
        state: typing.Optional[WorkflowsUpdateWorkflowPayloadV2State] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsUpdateWorkflowResultV2:
        """
        Updates a workflow

        Parameters
        ----------
        id : str
            ID of the workflow to update

        condition_groups : typing.Sequence[ConditionGroupPayloadV2]
            Conditions that apply to the workflow trigger

        continue_on_step_error : bool
            Whether to continue executing the workflow if a step fails

        expressions : typing.Sequence[ExpressionPayloadV2]
            The expressions to use in the workflow

        include_private_incidents : bool
            Whether to include private incidents

        name : str
            Name provided by the user when creating the workflow

        once_for : typing.Sequence[str]
            This workflow will run 'once for' a list of references

        runs_on_incident_modes : typing.Sequence[WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem]
            Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.

        runs_on_incidents : WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents
            Which incidents should the workflow be applied to?

        steps : typing.Sequence[StepConfigPayloadV2]
            Steps that are executed as part of the workflow

        annotations : typing.Optional[typing.Dict[str, str]]
            Annotations that track metadata about this resource

        delay : typing.Optional[WorkflowDelayV2]

        folder : typing.Optional[str]
            Folder to display the workflow in

        include_private_escalations : typing.Optional[bool]
            Whether to include private escalations

        shortform : typing.Optional[str]
            The shortform used to trigger this workflow (only applicable for manual triggers)

        state : typing.Optional[WorkflowsUpdateWorkflowPayloadV2State]
            What state this workflow is in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsUpdateWorkflowResultV2
            OK response.

        Examples
        --------
        from fern import (
            ConditionGroupPayloadV2,
            ConditionPayloadV2,
            EngineParamBindingPayloadV2,
            EngineParamBindingValuePayloadV2,
            ExpressionBranchesOptsPayloadV2,
            ExpressionBranchPayloadV2,
            ExpressionConcatenateOptsPayloadV2,
            ExpressionElseBranchPayloadV2,
            ExpressionFilterOptsPayloadV2,
            ExpressionNavigateOptsPayloadV2,
            ExpressionOperationPayloadV2,
            ExpressionParseOptsPayloadV2,
            ExpressionPayloadV2,
            IncidentIO,
            ReturnsMetaV2,
            StepConfigPayloadV2,
            WorkflowDelayV2,
        )

        client = IncidentIO()
        client.workflows_v2.updateworkflow(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
            annotations={"incident.io/terraform/version": "3.0.0"},
            condition_groups=[
                ConditionGroupPayloadV2(
                    conditions=[
                        ConditionPayloadV2(
                            operation="one_of",
                            param_bindings=[
                                EngineParamBindingPayloadV2(
                                    array_value=[
                                        EngineParamBindingValuePayloadV2(
                                            literal="SEV123",
                                            reference="incident.severity",
                                        )
                                    ],
                                    value=EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    ),
                                )
                            ],
                            subject="incident.severity",
                        )
                    ],
                )
            ],
            continue_on_step_error=True,
            delay=WorkflowDelayV2(
                conditions_apply_over_delay=False,
                for_seconds=60,
            ),
            expressions=[
                ExpressionPayloadV2(
                    else_branch=ExpressionElseBranchPayloadV2(
                        result=EngineParamBindingPayloadV2(
                            array_value=[
                                EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                )
                            ],
                            value=EngineParamBindingValuePayloadV2(
                                literal="SEV123",
                                reference="incident.severity",
                            ),
                        ),
                    ),
                    label="Team Slack channel",
                    operations=[
                        ExpressionOperationPayloadV2(
                            branches=ExpressionBranchesOptsPayloadV2(
                                branches=[
                                    ExpressionBranchPayloadV2(
                                        condition_groups=[
                                            ConditionGroupPayloadV2(
                                                conditions=[
                                                    ConditionPayloadV2(
                                                        operation="one_of",
                                                        param_bindings=[
                                                            EngineParamBindingPayloadV2(
                                                                array_value=[
                                                                    EngineParamBindingValuePayloadV2(
                                                                        literal="SEV123",
                                                                        reference="incident.severity",
                                                                    )
                                                                ],
                                                                value=EngineParamBindingValuePayloadV2(
                                                                    literal="SEV123",
                                                                    reference="incident.severity",
                                                                ),
                                                            )
                                                        ],
                                                        subject="incident.severity",
                                                    )
                                                ],
                                            )
                                        ],
                                        result=EngineParamBindingPayloadV2(
                                            array_value=[
                                                EngineParamBindingValuePayloadV2(
                                                    literal="SEV123",
                                                    reference="incident.severity",
                                                )
                                            ],
                                            value=EngineParamBindingValuePayloadV2(
                                                literal="SEV123",
                                                reference="incident.severity",
                                            ),
                                        ),
                                    )
                                ],
                                returns=ReturnsMetaV2(
                                    array=True,
                                    type="IncidentStatus",
                                ),
                            ),
                            concatenate=ExpressionConcatenateOptsPayloadV2(
                                reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                            ),
                            filter=ExpressionFilterOptsPayloadV2(
                                condition_groups=[
                                    ConditionGroupPayloadV2(
                                        conditions=[
                                            ConditionPayloadV2(
                                                operation="one_of",
                                                param_bindings=[
                                                    EngineParamBindingPayloadV2(
                                                        array_value=[
                                                            EngineParamBindingValuePayloadV2(
                                                                literal="SEV123",
                                                                reference="incident.severity",
                                                            )
                                                        ],
                                                        value=EngineParamBindingValuePayloadV2(
                                                            literal="SEV123",
                                                            reference="incident.severity",
                                                        ),
                                                    )
                                                ],
                                                subject="incident.severity",
                                            )
                                        ],
                                    )
                                ],
                            ),
                            navigate=ExpressionNavigateOptsPayloadV2(
                                reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                            ),
                            operation_type="navigate",
                            parse=ExpressionParseOptsPayloadV2(
                                returns=ReturnsMetaV2(
                                    array=True,
                                    type="IncidentStatus",
                                ),
                                source='metadata.annotations["github.com/repo"]',
                            ),
                        )
                    ],
                    reference="abc123",
                    root_reference="incident.status",
                )
            ],
            folder="My folder 01",
            include_private_escalations=True,
            include_private_incidents=True,
            name="My little workflow",
            once_for=["incident.url"],
            runs_on_incident_modes=["standard", "test", "retrospective"],
            runs_on_incidents="newly_created",
            shortform="page-the-ceo",
            state="active",
            steps=[
                StepConfigPayloadV2(
                    for_each="abc123",
                    id="abc123",
                    name="pagerduty.escalate",
                    param_bindings=[
                        EngineParamBindingPayloadV2(
                            array_value=[
                                EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                )
                            ],
                            value=EngineParamBindingValuePayloadV2(
                                literal="SEV123",
                                reference="incident.severity",
                            ),
                        )
                    ],
                )
            ],
        )
        """
        _response = self._raw_client.updateworkflow(
            id,
            condition_groups=condition_groups,
            continue_on_step_error=continue_on_step_error,
            expressions=expressions,
            include_private_incidents=include_private_incidents,
            name=name,
            once_for=once_for,
            runs_on_incident_modes=runs_on_incident_modes,
            runs_on_incidents=runs_on_incidents,
            steps=steps,
            annotations=annotations,
            delay=delay,
            folder=folder,
            include_private_escalations=include_private_escalations,
            shortform=shortform,
            state=state,
            request_options=request_options,
        )
        return _response.data

    def destroyworkflow(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Archives a workflow

        Parameters
        ----------
        id : str
            Unique identifier for the workflow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.workflows_v2.destroyworkflow(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.destroyworkflow(id, request_options=request_options)
        return _response.data


class AsyncWorkflowsV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkflowsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkflowsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkflowsV2Client
        """
        return self._raw_client

    async def listworkflows(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowsListWorkflowsResultV2:
        """
        List all workflows

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsListWorkflowsResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.workflows_v2.listworkflows()


        asyncio.run(main())
        """
        _response = await self._raw_client.listworkflows(request_options=request_options)
        return _response.data

    async def createworkflow(
        self,
        *,
        condition_groups: typing.Sequence[ConditionGroupPayloadV2],
        continue_on_step_error: bool,
        expressions: typing.Sequence[ExpressionPayloadV2],
        include_private_incidents: bool,
        name: str,
        once_for: typing.Sequence[str],
        runs_on_incident_modes: typing.Sequence[WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem],
        runs_on_incidents: WorkflowsCreateWorkflowPayloadV2RunsOnIncidents,
        steps: typing.Sequence[StepConfigPayloadV2],
        trigger: str,
        annotations: typing.Optional[typing.Dict[str, str]] = OMIT,
        delay: typing.Optional[WorkflowDelayV2] = OMIT,
        folder: typing.Optional[str] = OMIT,
        include_private_escalations: typing.Optional[bool] = OMIT,
        shortform: typing.Optional[str] = OMIT,
        state: typing.Optional[WorkflowsCreateWorkflowPayloadV2State] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsCreateWorkflowResultV2:
        """
        Create a new workflow

        Parameters
        ----------
        condition_groups : typing.Sequence[ConditionGroupPayloadV2]
            Conditions that apply to the workflow trigger

        continue_on_step_error : bool
            Whether to continue executing the workflow if a step fails

        expressions : typing.Sequence[ExpressionPayloadV2]
            The expressions to use in the workflow

        include_private_incidents : bool
            Whether to include private incidents

        name : str
            Name provided by the user when creating the workflow

        once_for : typing.Sequence[str]
            This workflow will run 'once for' a list of references

        runs_on_incident_modes : typing.Sequence[WorkflowsCreateWorkflowPayloadV2RunsOnIncidentModesItem]
            Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.

        runs_on_incidents : WorkflowsCreateWorkflowPayloadV2RunsOnIncidents
            Which incidents should the workflow be applied to?

        steps : typing.Sequence[StepConfigPayloadV2]
            Steps that are executed as part of the workflow

        trigger : str
            Trigger to set on the workflow

        annotations : typing.Optional[typing.Dict[str, str]]
            Annotations that track metadata about this resource

        delay : typing.Optional[WorkflowDelayV2]

        folder : typing.Optional[str]
            Folder to display the workflow in

        include_private_escalations : typing.Optional[bool]
            Whether to include private escalations

        shortform : typing.Optional[str]
            The shortform used to trigger this workflow (only applicable for manual triggers)

        state : typing.Optional[WorkflowsCreateWorkflowPayloadV2State]
            What state this workflow is in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsCreateWorkflowResultV2
            Created response.

        Examples
        --------
        import asyncio

        from fern import (
            AsyncIncidentIO,
            ConditionGroupPayloadV2,
            ConditionPayloadV2,
            EngineParamBindingPayloadV2,
            EngineParamBindingValuePayloadV2,
            ExpressionBranchesOptsPayloadV2,
            ExpressionBranchPayloadV2,
            ExpressionConcatenateOptsPayloadV2,
            ExpressionElseBranchPayloadV2,
            ExpressionFilterOptsPayloadV2,
            ExpressionNavigateOptsPayloadV2,
            ExpressionOperationPayloadV2,
            ExpressionParseOptsPayloadV2,
            ExpressionPayloadV2,
            ReturnsMetaV2,
            StepConfigPayloadV2,
            WorkflowDelayV2,
        )

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.workflows_v2.createworkflow(
                annotations={"incident.io/terraform/version": "3.0.0"},
                condition_groups=[
                    ConditionGroupPayloadV2(
                        conditions=[
                            ConditionPayloadV2(
                                operation="one_of",
                                param_bindings=[
                                    EngineParamBindingPayloadV2(
                                        array_value=[
                                            EngineParamBindingValuePayloadV2(
                                                literal="SEV123",
                                                reference="incident.severity",
                                            )
                                        ],
                                        value=EngineParamBindingValuePayloadV2(
                                            literal="SEV123",
                                            reference="incident.severity",
                                        ),
                                    )
                                ],
                                subject="incident.severity",
                            )
                        ],
                    )
                ],
                continue_on_step_error=True,
                delay=WorkflowDelayV2(
                    conditions_apply_over_delay=False,
                    for_seconds=60,
                ),
                expressions=[
                    ExpressionPayloadV2(
                        else_branch=ExpressionElseBranchPayloadV2(
                            result=EngineParamBindingPayloadV2(
                                array_value=[
                                    EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    )
                                ],
                                value=EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                ),
                            ),
                        ),
                        label="Team Slack channel",
                        operations=[
                            ExpressionOperationPayloadV2(
                                branches=ExpressionBranchesOptsPayloadV2(
                                    branches=[
                                        ExpressionBranchPayloadV2(
                                            condition_groups=[
                                                ConditionGroupPayloadV2(
                                                    conditions=[
                                                        ConditionPayloadV2(
                                                            operation="one_of",
                                                            param_bindings=[
                                                                EngineParamBindingPayloadV2(
                                                                    array_value=[
                                                                        EngineParamBindingValuePayloadV2(
                                                                            literal="SEV123",
                                                                            reference="incident.severity",
                                                                        )
                                                                    ],
                                                                    value=EngineParamBindingValuePayloadV2(
                                                                        literal="SEV123",
                                                                        reference="incident.severity",
                                                                    ),
                                                                )
                                                            ],
                                                            subject="incident.severity",
                                                        )
                                                    ],
                                                )
                                            ],
                                            result=EngineParamBindingPayloadV2(
                                                array_value=[
                                                    EngineParamBindingValuePayloadV2(
                                                        literal="SEV123",
                                                        reference="incident.severity",
                                                    )
                                                ],
                                                value=EngineParamBindingValuePayloadV2(
                                                    literal="SEV123",
                                                    reference="incident.severity",
                                                ),
                                            ),
                                        )
                                    ],
                                    returns=ReturnsMetaV2(
                                        array=True,
                                        type="IncidentStatus",
                                    ),
                                ),
                                concatenate=ExpressionConcatenateOptsPayloadV2(
                                    reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                                ),
                                filter=ExpressionFilterOptsPayloadV2(
                                    condition_groups=[
                                        ConditionGroupPayloadV2(
                                            conditions=[
                                                ConditionPayloadV2(
                                                    operation="one_of",
                                                    param_bindings=[
                                                        EngineParamBindingPayloadV2(
                                                            array_value=[
                                                                EngineParamBindingValuePayloadV2(
                                                                    literal="SEV123",
                                                                    reference="incident.severity",
                                                                )
                                                            ],
                                                            value=EngineParamBindingValuePayloadV2(
                                                                literal="SEV123",
                                                                reference="incident.severity",
                                                            ),
                                                        )
                                                    ],
                                                    subject="incident.severity",
                                                )
                                            ],
                                        )
                                    ],
                                ),
                                navigate=ExpressionNavigateOptsPayloadV2(
                                    reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                                ),
                                operation_type="navigate",
                                parse=ExpressionParseOptsPayloadV2(
                                    returns=ReturnsMetaV2(
                                        array=True,
                                        type="IncidentStatus",
                                    ),
                                    source='metadata.annotations["github.com/repo"]',
                                ),
                            )
                        ],
                        reference="abc123",
                        root_reference="incident.status",
                    )
                ],
                folder="My folder 01",
                include_private_escalations=True,
                include_private_incidents=True,
                name="My little workflow",
                once_for=["incident.url"],
                runs_on_incident_modes=["standard", "test", "retrospective"],
                runs_on_incidents="newly_created",
                shortform="page-the-ceo",
                state="active",
                steps=[
                    StepConfigPayloadV2(
                        for_each="abc123",
                        id="abc123",
                        name="pagerduty.escalate",
                        param_bindings=[
                            EngineParamBindingPayloadV2(
                                array_value=[
                                    EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    )
                                ],
                                value=EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                ),
                            )
                        ],
                    )
                ],
                trigger="incident.updated",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.createworkflow(
            condition_groups=condition_groups,
            continue_on_step_error=continue_on_step_error,
            expressions=expressions,
            include_private_incidents=include_private_incidents,
            name=name,
            once_for=once_for,
            runs_on_incident_modes=runs_on_incident_modes,
            runs_on_incidents=runs_on_incidents,
            steps=steps,
            trigger=trigger,
            annotations=annotations,
            delay=delay,
            folder=folder,
            include_private_escalations=include_private_escalations,
            shortform=shortform,
            state=state,
            request_options=request_options,
        )
        return _response.data

    async def showworkflow(
        self,
        id: str,
        *,
        skip_step_upgrades: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsShowWorkflowResultV2:
        """
        Show a workflow by ID

        Parameters
        ----------
        id : str
            Unique identifier for the workflow

        skip_step_upgrades : typing.Optional[bool]
            Skips workflow step upgrades, when the parameters for an existing workflow step change

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsShowWorkflowResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.workflows_v2.showworkflow(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
                skip_step_upgrades=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.showworkflow(
            id, skip_step_upgrades=skip_step_upgrades, request_options=request_options
        )
        return _response.data

    async def updateworkflow(
        self,
        id: str,
        *,
        condition_groups: typing.Sequence[ConditionGroupPayloadV2],
        continue_on_step_error: bool,
        expressions: typing.Sequence[ExpressionPayloadV2],
        include_private_incidents: bool,
        name: str,
        once_for: typing.Sequence[str],
        runs_on_incident_modes: typing.Sequence[WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem],
        runs_on_incidents: WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents,
        steps: typing.Sequence[StepConfigPayloadV2],
        annotations: typing.Optional[typing.Dict[str, str]] = OMIT,
        delay: typing.Optional[WorkflowDelayV2] = OMIT,
        folder: typing.Optional[str] = OMIT,
        include_private_escalations: typing.Optional[bool] = OMIT,
        shortform: typing.Optional[str] = OMIT,
        state: typing.Optional[WorkflowsUpdateWorkflowPayloadV2State] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowsUpdateWorkflowResultV2:
        """
        Updates a workflow

        Parameters
        ----------
        id : str
            ID of the workflow to update

        condition_groups : typing.Sequence[ConditionGroupPayloadV2]
            Conditions that apply to the workflow trigger

        continue_on_step_error : bool
            Whether to continue executing the workflow if a step fails

        expressions : typing.Sequence[ExpressionPayloadV2]
            The expressions to use in the workflow

        include_private_incidents : bool
            Whether to include private incidents

        name : str
            Name provided by the user when creating the workflow

        once_for : typing.Sequence[str]
            This workflow will run 'once for' a list of references

        runs_on_incident_modes : typing.Sequence[WorkflowsUpdateWorkflowPayloadV2RunsOnIncidentModesItem]
            Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.

        runs_on_incidents : WorkflowsUpdateWorkflowPayloadV2RunsOnIncidents
            Which incidents should the workflow be applied to?

        steps : typing.Sequence[StepConfigPayloadV2]
            Steps that are executed as part of the workflow

        annotations : typing.Optional[typing.Dict[str, str]]
            Annotations that track metadata about this resource

        delay : typing.Optional[WorkflowDelayV2]

        folder : typing.Optional[str]
            Folder to display the workflow in

        include_private_escalations : typing.Optional[bool]
            Whether to include private escalations

        shortform : typing.Optional[str]
            The shortform used to trigger this workflow (only applicable for manual triggers)

        state : typing.Optional[WorkflowsUpdateWorkflowPayloadV2State]
            What state this workflow is in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowsUpdateWorkflowResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import (
            AsyncIncidentIO,
            ConditionGroupPayloadV2,
            ConditionPayloadV2,
            EngineParamBindingPayloadV2,
            EngineParamBindingValuePayloadV2,
            ExpressionBranchesOptsPayloadV2,
            ExpressionBranchPayloadV2,
            ExpressionConcatenateOptsPayloadV2,
            ExpressionElseBranchPayloadV2,
            ExpressionFilterOptsPayloadV2,
            ExpressionNavigateOptsPayloadV2,
            ExpressionOperationPayloadV2,
            ExpressionParseOptsPayloadV2,
            ExpressionPayloadV2,
            ReturnsMetaV2,
            StepConfigPayloadV2,
            WorkflowDelayV2,
        )

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.workflows_v2.updateworkflow(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
                annotations={"incident.io/terraform/version": "3.0.0"},
                condition_groups=[
                    ConditionGroupPayloadV2(
                        conditions=[
                            ConditionPayloadV2(
                                operation="one_of",
                                param_bindings=[
                                    EngineParamBindingPayloadV2(
                                        array_value=[
                                            EngineParamBindingValuePayloadV2(
                                                literal="SEV123",
                                                reference="incident.severity",
                                            )
                                        ],
                                        value=EngineParamBindingValuePayloadV2(
                                            literal="SEV123",
                                            reference="incident.severity",
                                        ),
                                    )
                                ],
                                subject="incident.severity",
                            )
                        ],
                    )
                ],
                continue_on_step_error=True,
                delay=WorkflowDelayV2(
                    conditions_apply_over_delay=False,
                    for_seconds=60,
                ),
                expressions=[
                    ExpressionPayloadV2(
                        else_branch=ExpressionElseBranchPayloadV2(
                            result=EngineParamBindingPayloadV2(
                                array_value=[
                                    EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    )
                                ],
                                value=EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                ),
                            ),
                        ),
                        label="Team Slack channel",
                        operations=[
                            ExpressionOperationPayloadV2(
                                branches=ExpressionBranchesOptsPayloadV2(
                                    branches=[
                                        ExpressionBranchPayloadV2(
                                            condition_groups=[
                                                ConditionGroupPayloadV2(
                                                    conditions=[
                                                        ConditionPayloadV2(
                                                            operation="one_of",
                                                            param_bindings=[
                                                                EngineParamBindingPayloadV2(
                                                                    array_value=[
                                                                        EngineParamBindingValuePayloadV2(
                                                                            literal="SEV123",
                                                                            reference="incident.severity",
                                                                        )
                                                                    ],
                                                                    value=EngineParamBindingValuePayloadV2(
                                                                        literal="SEV123",
                                                                        reference="incident.severity",
                                                                    ),
                                                                )
                                                            ],
                                                            subject="incident.severity",
                                                        )
                                                    ],
                                                )
                                            ],
                                            result=EngineParamBindingPayloadV2(
                                                array_value=[
                                                    EngineParamBindingValuePayloadV2(
                                                        literal="SEV123",
                                                        reference="incident.severity",
                                                    )
                                                ],
                                                value=EngineParamBindingValuePayloadV2(
                                                    literal="SEV123",
                                                    reference="incident.severity",
                                                ),
                                            ),
                                        )
                                    ],
                                    returns=ReturnsMetaV2(
                                        array=True,
                                        type="IncidentStatus",
                                    ),
                                ),
                                concatenate=ExpressionConcatenateOptsPayloadV2(
                                    reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                                ),
                                filter=ExpressionFilterOptsPayloadV2(
                                    condition_groups=[
                                        ConditionGroupPayloadV2(
                                            conditions=[
                                                ConditionPayloadV2(
                                                    operation="one_of",
                                                    param_bindings=[
                                                        EngineParamBindingPayloadV2(
                                                            array_value=[
                                                                EngineParamBindingValuePayloadV2(
                                                                    literal="SEV123",
                                                                    reference="incident.severity",
                                                                )
                                                            ],
                                                            value=EngineParamBindingValuePayloadV2(
                                                                literal="SEV123",
                                                                reference="incident.severity",
                                                            ),
                                                        )
                                                    ],
                                                    subject="incident.severity",
                                                )
                                            ],
                                        )
                                    ],
                                ),
                                navigate=ExpressionNavigateOptsPayloadV2(
                                    reference='catalog_attribute["01FCNDV6P870EA6S7TK1DSYD5H"]',
                                ),
                                operation_type="navigate",
                                parse=ExpressionParseOptsPayloadV2(
                                    returns=ReturnsMetaV2(
                                        array=True,
                                        type="IncidentStatus",
                                    ),
                                    source='metadata.annotations["github.com/repo"]',
                                ),
                            )
                        ],
                        reference="abc123",
                        root_reference="incident.status",
                    )
                ],
                folder="My folder 01",
                include_private_escalations=True,
                include_private_incidents=True,
                name="My little workflow",
                once_for=["incident.url"],
                runs_on_incident_modes=["standard", "test", "retrospective"],
                runs_on_incidents="newly_created",
                shortform="page-the-ceo",
                state="active",
                steps=[
                    StepConfigPayloadV2(
                        for_each="abc123",
                        id="abc123",
                        name="pagerduty.escalate",
                        param_bindings=[
                            EngineParamBindingPayloadV2(
                                array_value=[
                                    EngineParamBindingValuePayloadV2(
                                        literal="SEV123",
                                        reference="incident.severity",
                                    )
                                ],
                                value=EngineParamBindingValuePayloadV2(
                                    literal="SEV123",
                                    reference="incident.severity",
                                ),
                            )
                        ],
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.updateworkflow(
            id,
            condition_groups=condition_groups,
            continue_on_step_error=continue_on_step_error,
            expressions=expressions,
            include_private_incidents=include_private_incidents,
            name=name,
            once_for=once_for,
            runs_on_incident_modes=runs_on_incident_modes,
            runs_on_incidents=runs_on_incidents,
            steps=steps,
            annotations=annotations,
            delay=delay,
            folder=folder,
            include_private_escalations=include_private_escalations,
            shortform=shortform,
            state=state,
            request_options=request_options,
        )
        return _response.data

    async def destroyworkflow(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Archives a workflow

        Parameters
        ----------
        id : str
            Unique identifier for the workflow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.workflows_v2.destroyworkflow(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.destroyworkflow(id, request_options=request_options)
        return _response.data
