# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.actions_list_result_v2 import ActionsListResultV2
from ..types.actions_show_result_v2 import ActionsShowResultV2
from .raw_client import AsyncRawActionsV2Client, RawActionsV2Client
from .types.actions_v2list_request_incident_mode import ActionsV2ListRequestIncidentMode


class ActionsV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawActionsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawActionsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawActionsV2Client
        """
        return self._raw_client

    def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        incident_mode: typing.Optional[ActionsV2ListRequestIncidentMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ActionsListResultV2:
        """
        List all actions for an organisation.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Find actions related to this incident

        incident_mode : typing.Optional[ActionsV2ListRequestIncidentMode]
            Filter to actions from incidents of the given mode. If not set, only actions from `standard` and `retrospective` incidents are returned

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActionsListResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.actions_v2.list(
            incident_id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.list(
            incident_id=incident_id, incident_mode=incident_mode, request_options=request_options
        )
        return _response.data

    def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ActionsShowResultV2:
        """
        Get a single incident action.

        Parameters
        ----------
        id : str
            Unique identifier for the action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActionsShowResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.actions_v2.show(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.show(id, request_options=request_options)
        return _response.data


class AsyncActionsV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawActionsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawActionsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawActionsV2Client
        """
        return self._raw_client

    async def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        incident_mode: typing.Optional[ActionsV2ListRequestIncidentMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ActionsListResultV2:
        """
        List all actions for an organisation.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Find actions related to this incident

        incident_mode : typing.Optional[ActionsV2ListRequestIncidentMode]
            Filter to actions from incidents of the given mode. If not set, only actions from `standard` and `retrospective` incidents are returned

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActionsListResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.actions_v2.list(
                incident_id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            incident_id=incident_id, incident_mode=incident_mode, request_options=request_options
        )
        return _response.data

    async def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ActionsShowResultV2:
        """
        Get a single incident action.

        Parameters
        ----------
        id : str
            Unique identifier for the action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActionsShowResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.actions_v2.show(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show(id, request_options=request_options)
        return _response.data
