# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.actions_list_result_v2 import ActionsListResultV2
from ..types.actions_show_result_v2 import ActionsShowResultV2
from .types.actions_v2list_request_incident_mode import ActionsV2ListRequestIncidentMode


class RawActionsV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        incident_mode: typing.Optional[ActionsV2ListRequestIncidentMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ActionsListResultV2]:
        """
        List all actions for an organisation.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Find actions related to this incident

        incident_mode : typing.Optional[ActionsV2ListRequestIncidentMode]
            Filter to actions from incidents of the given mode. If not set, only actions from `standard` and `retrospective` incidents are returned

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActionsListResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/actions",
            method="GET",
            params={
                "incident_id": incident_id,
                "incident_mode": incident_mode,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActionsListResultV2,
                    parse_obj_as(
                        type_=ActionsListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ActionsShowResultV2]:
        """
        Get a single incident action.

        Parameters
        ----------
        id : str
            Unique identifier for the action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ActionsShowResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/actions/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActionsShowResultV2,
                    parse_obj_as(
                        type_=ActionsShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawActionsV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        incident_mode: typing.Optional[ActionsV2ListRequestIncidentMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ActionsListResultV2]:
        """
        List all actions for an organisation.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Find actions related to this incident

        incident_mode : typing.Optional[ActionsV2ListRequestIncidentMode]
            Filter to actions from incidents of the given mode. If not set, only actions from `standard` and `retrospective` incidents are returned

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActionsListResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/actions",
            method="GET",
            params={
                "incident_id": incident_id,
                "incident_mode": incident_mode,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActionsListResultV2,
                    parse_obj_as(
                        type_=ActionsListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ActionsShowResultV2]:
        """
        Get a single incident action.

        Parameters
        ----------
        id : str
            Unique identifier for the action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ActionsShowResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/actions/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ActionsShowResultV2,
                    parse_obj_as(
                        type_=ActionsShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
