# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.custom_field_entry_payload_v1 import CustomFieldEntryPayloadV1
from ..types.incident_role_assignment_payload_v1 import IncidentRoleAssignmentPayloadV1
from ..types.incidents_create_result_v1 import IncidentsCreateResultV1
from ..types.incidents_list_result_v1 import IncidentsListResultV1
from ..types.incidents_show_result_v1 import IncidentsShowResultV1
from .types.incidents_create_payload_v1mode import IncidentsCreatePayloadV1Mode
from .types.incidents_create_payload_v1status import IncidentsCreatePayloadV1Status
from .types.incidents_create_payload_v1visibility import IncidentsCreatePayloadV1Visibility

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawIncidentsV1Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        status: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IncidentsListResultV1]:
        """
        List all incidents for an organisation.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        status : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter for incidents in these statuses

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IncidentsListResultV1]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/incidents",
            method="GET",
            params={
                "page_size": page_size,
                "after": after,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsListResultV1,
                    parse_obj_as(
                        type_=IncidentsListResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        idempotency_key: str,
        visibility: IncidentsCreatePayloadV1Visibility,
        custom_field_entries: typing.Optional[typing.Sequence[CustomFieldEntryPayloadV1]] = OMIT,
        incident_role_assignments: typing.Optional[typing.Sequence[IncidentRoleAssignmentPayloadV1]] = OMIT,
        incident_type_id: typing.Optional[str] = OMIT,
        mode: typing.Optional[IncidentsCreatePayloadV1Mode] = OMIT,
        name: typing.Optional[str] = OMIT,
        severity_id: typing.Optional[str] = OMIT,
        slack_team_id: typing.Optional[str] = OMIT,
        source_message_channel_id: typing.Optional[str] = OMIT,
        source_message_timestamp: typing.Optional[str] = OMIT,
        status: typing.Optional[IncidentsCreatePayloadV1Status] = OMIT,
        summary: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IncidentsCreateResultV1]:
        """
        Create a new incident.

        Parameters
        ----------
        idempotency_key : str
            Unique string used to de-duplicate incident create requests

        visibility : IncidentsCreatePayloadV1Visibility
            Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access).

        custom_field_entries : typing.Optional[typing.Sequence[CustomFieldEntryPayloadV1]]
            Set the incident's custom fields to these values

        incident_role_assignments : typing.Optional[typing.Sequence[IncidentRoleAssignmentPayloadV1]]
            Assign incident roles to these people

        incident_type_id : typing.Optional[str]
            Incident type to create this incident as

        mode : typing.Optional[IncidentsCreatePayloadV1Mode]
            Whether the incident is real or test

        name : typing.Optional[str]
            Explanation of the incident

        severity_id : typing.Optional[str]
            Severity to create incident as

        slack_team_id : typing.Optional[str]
            ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams.

        source_message_channel_id : typing.Optional[str]
            Channel ID of the source message, if this incident was created from one

        source_message_timestamp : typing.Optional[str]
            Timestamp of the source message, if this incident was created from one

        status : typing.Optional[IncidentsCreatePayloadV1Status]
            Current status of the incident

        summary : typing.Optional[str]
            Detailed description of the incident

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IncidentsCreateResultV1]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/incidents",
            method="POST",
            json={
                "custom_field_entries": convert_and_respect_annotation_metadata(
                    object_=custom_field_entries,
                    annotation=typing.Sequence[CustomFieldEntryPayloadV1],
                    direction="write",
                ),
                "idempotency_key": idempotency_key,
                "incident_role_assignments": convert_and_respect_annotation_metadata(
                    object_=incident_role_assignments,
                    annotation=typing.Sequence[IncidentRoleAssignmentPayloadV1],
                    direction="write",
                ),
                "incident_type_id": incident_type_id,
                "mode": mode,
                "name": name,
                "severity_id": severity_id,
                "slack_team_id": slack_team_id,
                "source_message_channel_id": source_message_channel_id,
                "source_message_timestamp": source_message_timestamp,
                "status": status,
                "summary": summary,
                "visibility": visibility,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsCreateResultV1,
                    parse_obj_as(
                        type_=IncidentsCreateResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[IncidentsShowResultV1]:
        """
        Get a single incident.

        Parameters
        ----------
        id : str
            Unique identifier for the incident

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IncidentsShowResultV1]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/incidents/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsShowResultV1,
                    parse_obj_as(
                        type_=IncidentsShowResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawIncidentsV1Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        status: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IncidentsListResultV1]:
        """
        List all incidents for an organisation.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        status : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter for incidents in these statuses

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IncidentsListResultV1]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/incidents",
            method="GET",
            params={
                "page_size": page_size,
                "after": after,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsListResultV1,
                    parse_obj_as(
                        type_=IncidentsListResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        idempotency_key: str,
        visibility: IncidentsCreatePayloadV1Visibility,
        custom_field_entries: typing.Optional[typing.Sequence[CustomFieldEntryPayloadV1]] = OMIT,
        incident_role_assignments: typing.Optional[typing.Sequence[IncidentRoleAssignmentPayloadV1]] = OMIT,
        incident_type_id: typing.Optional[str] = OMIT,
        mode: typing.Optional[IncidentsCreatePayloadV1Mode] = OMIT,
        name: typing.Optional[str] = OMIT,
        severity_id: typing.Optional[str] = OMIT,
        slack_team_id: typing.Optional[str] = OMIT,
        source_message_channel_id: typing.Optional[str] = OMIT,
        source_message_timestamp: typing.Optional[str] = OMIT,
        status: typing.Optional[IncidentsCreatePayloadV1Status] = OMIT,
        summary: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IncidentsCreateResultV1]:
        """
        Create a new incident.

        Parameters
        ----------
        idempotency_key : str
            Unique string used to de-duplicate incident create requests

        visibility : IncidentsCreatePayloadV1Visibility
            Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access).

        custom_field_entries : typing.Optional[typing.Sequence[CustomFieldEntryPayloadV1]]
            Set the incident's custom fields to these values

        incident_role_assignments : typing.Optional[typing.Sequence[IncidentRoleAssignmentPayloadV1]]
            Assign incident roles to these people

        incident_type_id : typing.Optional[str]
            Incident type to create this incident as

        mode : typing.Optional[IncidentsCreatePayloadV1Mode]
            Whether the incident is real or test

        name : typing.Optional[str]
            Explanation of the incident

        severity_id : typing.Optional[str]
            Severity to create incident as

        slack_team_id : typing.Optional[str]
            ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams.

        source_message_channel_id : typing.Optional[str]
            Channel ID of the source message, if this incident was created from one

        source_message_timestamp : typing.Optional[str]
            Timestamp of the source message, if this incident was created from one

        status : typing.Optional[IncidentsCreatePayloadV1Status]
            Current status of the incident

        summary : typing.Optional[str]
            Detailed description of the incident

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IncidentsCreateResultV1]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/incidents",
            method="POST",
            json={
                "custom_field_entries": convert_and_respect_annotation_metadata(
                    object_=custom_field_entries,
                    annotation=typing.Sequence[CustomFieldEntryPayloadV1],
                    direction="write",
                ),
                "idempotency_key": idempotency_key,
                "incident_role_assignments": convert_and_respect_annotation_metadata(
                    object_=incident_role_assignments,
                    annotation=typing.Sequence[IncidentRoleAssignmentPayloadV1],
                    direction="write",
                ),
                "incident_type_id": incident_type_id,
                "mode": mode,
                "name": name,
                "severity_id": severity_id,
                "slack_team_id": slack_team_id,
                "source_message_channel_id": source_message_channel_id,
                "source_message_timestamp": source_message_timestamp,
                "status": status,
                "summary": summary,
                "visibility": visibility,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsCreateResultV1,
                    parse_obj_as(
                        type_=IncidentsCreateResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[IncidentsShowResultV1]:
        """
        Get a single incident.

        Parameters
        ----------
        id : str
            Unique identifier for the incident

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IncidentsShowResultV1]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/incidents/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IncidentsShowResultV1,
                    parse_obj_as(
                        type_=IncidentsShowResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
