# This file was auto-generated by Fern from our API Definition.

import typing

IncidentsCreatePayloadV1Status = typing.Union[
    typing.Literal["triage", "investigating", "fixing", "monitoring", "closed", "declined"], typing.Any
]
