# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.ip_allowlist_item_v1 import IpAllowlistItemV1
from ..types.ip_allowlists_show_ip_allowlist_result_v1 import IpAllowlistsShowIpAllowlistResultV1
from ..types.ip_allowlists_update_ip_allowlist_result_v1 import IpAllowlistsUpdateIpAllowlistResultV1

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawIpallowlistsV1Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def showipallowlist(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[IpAllowlistsShowIpAllowlistResultV1]:
        """
        Show the IP allowlist for your organisation

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IpAllowlistsShowIpAllowlistResultV1]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/ip_allowlists",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IpAllowlistsShowIpAllowlistResultV1,
                    parse_obj_as(
                        type_=IpAllowlistsShowIpAllowlistResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def updateipallowlist(
        self,
        *,
        allowlist: typing.Sequence[IpAllowlistItemV1],
        enabled: bool,
        version: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IpAllowlistsUpdateIpAllowlistResultV1]:
        """
        Update the IP allowlist for your organisation

        Parameters
        ----------
        allowlist : typing.Sequence[IpAllowlistItemV1]
            A list of IP addresses or CIDR prefixes to allow

        enabled : bool
            Whether this IP allowlist is enabled or not

        version : int
            The version of this IP allowlist

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IpAllowlistsUpdateIpAllowlistResultV1]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/ip_allowlists",
            method="PUT",
            json={
                "allowlist": convert_and_respect_annotation_metadata(
                    object_=allowlist, annotation=typing.Sequence[IpAllowlistItemV1], direction="write"
                ),
                "enabled": enabled,
                "version": version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IpAllowlistsUpdateIpAllowlistResultV1,
                    parse_obj_as(
                        type_=IpAllowlistsUpdateIpAllowlistResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawIpallowlistsV1Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def showipallowlist(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[IpAllowlistsShowIpAllowlistResultV1]:
        """
        Show the IP allowlist for your organisation

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IpAllowlistsShowIpAllowlistResultV1]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/ip_allowlists",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IpAllowlistsShowIpAllowlistResultV1,
                    parse_obj_as(
                        type_=IpAllowlistsShowIpAllowlistResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def updateipallowlist(
        self,
        *,
        allowlist: typing.Sequence[IpAllowlistItemV1],
        enabled: bool,
        version: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IpAllowlistsUpdateIpAllowlistResultV1]:
        """
        Update the IP allowlist for your organisation

        Parameters
        ----------
        allowlist : typing.Sequence[IpAllowlistItemV1]
            A list of IP addresses or CIDR prefixes to allow

        enabled : bool
            Whether this IP allowlist is enabled or not

        version : int
            The version of this IP allowlist

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IpAllowlistsUpdateIpAllowlistResultV1]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/ip_allowlists",
            method="PUT",
            json={
                "allowlist": convert_and_respect_annotation_metadata(
                    object_=allowlist, annotation=typing.Sequence[IpAllowlistItemV1], direction="write"
                ),
                "enabled": enabled,
                "version": version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IpAllowlistsUpdateIpAllowlistResultV1,
                    parse_obj_as(
                        type_=IpAllowlistsUpdateIpAllowlistResultV1,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
