# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.custom_field_options_create_result_v1 import CustomFieldOptionsCreateResultV1
from ..types.custom_field_options_list_result_v1 import CustomFieldOptionsListResultV1
from ..types.custom_field_options_show_result_v1 import CustomFieldOptionsShowResultV1
from ..types.custom_field_options_update_result_v1 import CustomFieldOptionsUpdateResultV1
from .raw_client import AsyncRawCustomFieldOptionsV1Client, RawCustomFieldOptionsV1Client

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CustomFieldOptionsV1Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomFieldOptionsV1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomFieldOptionsV1Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomFieldOptionsV1Client
        """
        return self._raw_client

    def list(
        self,
        *,
        custom_field_id: str,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomFieldOptionsListResultV1:
        """
        Show custom field options for a custom field

        Parameters
        ----------
        custom_field_id : str
            The custom field to list options for.

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            A custom field option's ID. This endpoint will return a list of custom field options created after this option.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsListResultV1
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.custom_field_options_v1.list(
            page_size=25,
            after="01G0J1EXE7AXZ2C93K61WBPYEH",
            custom_field_id="01FCNDV6P870EA6S7TK1DSYD5H",
        )
        """
        _response = self._raw_client.list(
            custom_field_id=custom_field_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data

    def create(
        self,
        *,
        custom_field_id: str,
        value: str,
        sort_key: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomFieldOptionsCreateResultV1:
        """
        Create a custom field option. If the sort key is not supplied, it'll default to 1000, so the option appears near the end of the list.

        Parameters
        ----------
        custom_field_id : str
            ID of the custom field this option belongs to

        value : str
            Human readable name for the custom field option

        sort_key : typing.Optional[int]
            Sort key used to order the custom field options correctly

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsCreateResultV1
            Created response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.custom_field_options_v1.create(
            custom_field_id="01FCNDV6P870EA6S7TK1DSYDG0",
            sort_key=10,
            value="Product",
        )
        """
        _response = self._raw_client.create(
            custom_field_id=custom_field_id, value=value, sort_key=sort_key, request_options=request_options
        )
        return _response.data

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CustomFieldOptionsShowResultV1:
        """
        Get a single custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsShowResultV1
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.custom_field_options_v1.show(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.show(id, request_options=request_options)
        return _response.data

    def update(
        self, id: str, *, sort_key: int, value: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CustomFieldOptionsUpdateResultV1:
        """
        Update a custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        sort_key : int
            Sort key used to order the custom field options correctly

        value : str
            Human readable name for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsUpdateResultV1
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.custom_field_options_v1.update(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
            sort_key=10,
            value="Product",
        )
        """
        _response = self._raw_client.update(id, sort_key=sort_key, value=value, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.custom_field_options_v1.delete(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncCustomFieldOptionsV1Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomFieldOptionsV1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomFieldOptionsV1Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomFieldOptionsV1Client
        """
        return self._raw_client

    async def list(
        self,
        *,
        custom_field_id: str,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomFieldOptionsListResultV1:
        """
        Show custom field options for a custom field

        Parameters
        ----------
        custom_field_id : str
            The custom field to list options for.

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            A custom field option's ID. This endpoint will return a list of custom field options created after this option.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsListResultV1
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.custom_field_options_v1.list(
                page_size=25,
                after="01G0J1EXE7AXZ2C93K61WBPYEH",
                custom_field_id="01FCNDV6P870EA6S7TK1DSYD5H",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            custom_field_id=custom_field_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        custom_field_id: str,
        value: str,
        sort_key: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomFieldOptionsCreateResultV1:
        """
        Create a custom field option. If the sort key is not supplied, it'll default to 1000, so the option appears near the end of the list.

        Parameters
        ----------
        custom_field_id : str
            ID of the custom field this option belongs to

        value : str
            Human readable name for the custom field option

        sort_key : typing.Optional[int]
            Sort key used to order the custom field options correctly

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsCreateResultV1
            Created response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.custom_field_options_v1.create(
                custom_field_id="01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key=10,
                value="Product",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            custom_field_id=custom_field_id, value=value, sort_key=sort_key, request_options=request_options
        )
        return _response.data

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CustomFieldOptionsShowResultV1:
        """
        Get a single custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsShowResultV1
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.custom_field_options_v1.show(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show(id, request_options=request_options)
        return _response.data

    async def update(
        self, id: str, *, sort_key: int, value: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CustomFieldOptionsUpdateResultV1:
        """
        Update a custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        sort_key : int
            Sort key used to order the custom field options correctly

        value : str
            Human readable name for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomFieldOptionsUpdateResultV1
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.custom_field_options_v1.update(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key=10,
                value="Product",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, sort_key=sort_key, value=value, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a custom field option

        Parameters
        ----------
        id : str
            Unique identifier for the custom field option

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.custom_field_options_v1.delete(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
