# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.incident_updates_list_result_v2 import IncidentUpdatesListResultV2
from .raw_client import AsyncRawIncidentUpdatesV2Client, RawIncidentUpdatesV2Client


class IncidentUpdatesV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIncidentUpdatesV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIncidentUpdatesV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIncidentUpdatesV2Client
        """
        return self._raw_client

    def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncidentUpdatesListResultV2:
        """
        List all incident updates for an organisation, or for a specific incident.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Incident whose updates you want to list

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentUpdatesListResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.incident_updates_v2.list(
            incident_id="01G0J1EXE7AXZ2C93K61WBPYEH",
            page_size=25,
            after="01FDAG4SAP5TYPT98WGR2N7W91",
        )
        """
        _response = self._raw_client.list(
            incident_id=incident_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data


class AsyncIncidentUpdatesV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIncidentUpdatesV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIncidentUpdatesV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIncidentUpdatesV2Client
        """
        return self._raw_client

    async def list(
        self,
        *,
        incident_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncidentUpdatesListResultV2:
        """
        List all incident updates for an organisation, or for a specific incident.

        Parameters
        ----------
        incident_id : typing.Optional[str]
            Incident whose updates you want to list

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentUpdatesListResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.incident_updates_v2.list(
                incident_id="01G0J1EXE7AXZ2C93K61WBPYEH",
                page_size=25,
                after="01FDAG4SAP5TYPT98WGR2N7W91",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            incident_id=incident_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data
