# This file was auto-generated by Fern from our API Definition.

import typing

ActionsV2ListRequestIncidentMode = typing.Union[
    typing.Literal["standard", "retrospective", "test", "tutorial", "stream"], typing.Any
]
