# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.incident_timestamps_list_result_v2 import IncidentTimestampsListResultV2
from ..types.incident_timestamps_show_result_v2 import IncidentTimestampsShowResultV2
from .raw_client import AsyncRawIncidentTimestampsV2Client, RawIncidentTimestampsV2Client


class IncidentTimestampsV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIncidentTimestampsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIncidentTimestampsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIncidentTimestampsV2Client
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> IncidentTimestampsListResultV2:
        """
        List all incident timestamps for an organisation.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentTimestampsListResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.incident_timestamps_v2.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> IncidentTimestampsShowResultV2:
        """
        Get a single incident timestamp.

        Parameters
        ----------
        id : str
            Unique ID of this incident timestamp

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentTimestampsShowResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.incident_timestamps_v2.show(
            id="01FCNDV6P870EA6S7TK1DSYD5H",
        )
        """
        _response = self._raw_client.show(id, request_options=request_options)
        return _response.data


class AsyncIncidentTimestampsV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIncidentTimestampsV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIncidentTimestampsV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIncidentTimestampsV2Client
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> IncidentTimestampsListResultV2:
        """
        List all incident timestamps for an organisation.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentTimestampsListResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.incident_timestamps_v2.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> IncidentTimestampsShowResultV2:
        """
        Get a single incident timestamp.

        Parameters
        ----------
        id : str
            Unique ID of this incident timestamp

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncidentTimestampsShowResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.incident_timestamps_v2.show(
                id="01FCNDV6P870EA6S7TK1DSYD5H",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show(id, request_options=request_options)
        return _response.data
