# This file was auto-generated by Fern from our API Definition.

import typing

IncidentAttachmentsCreatePayloadV1ResourceResourceType = typing.Union[
    typing.Literal[
        "pager_duty_incident",
        "opsgenie_alert",
        "datadog_monitor_alert",
        "github_pull_request",
        "gitlab_merge_request",
        "sentry_issue",
        "jira_issue",
        "jsm_alert",
        "atlassian_statuspage_incident",
        "zendesk_ticket",
        "google_calendar_event",
        "outlook_calendar_event",
        "slack_file",
        "scrubbed",
        "statuspage_incident",
    ],
    typing.Any,
]
