# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.utilities_identity_result_v1 import UtilitiesIdentityResultV1
from .raw_client import AsyncRawUtilitiesV1Client, RawUtilitiesV1Client


class UtilitiesV1Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUtilitiesV1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUtilitiesV1Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUtilitiesV1Client
        """
        return self._raw_client

    def identity(self, *, request_options: typing.Optional[RequestOptions] = None) -> UtilitiesIdentityResultV1:
        """
        Test if your API key is valid, and which roles it has.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UtilitiesIdentityResultV1
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.utilities_v1.identity()
        """
        _response = self._raw_client.identity(request_options=request_options)
        return _response.data

    def openapi(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Iterator[bytes]:
        """
        Get the OpenAPI (v2) definition.

        **DEPRECATED**: Please use the OpenAPIV3 endpoint instead. The schema returned from this endpoint does not contain new options and endpoints added in 2025 and later.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK response.
        """
        with self._raw_client.openapi(request_options=request_options) as r:
            yield from r.data

    def openapiv3(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Iterator[bytes]:
        """
        Get the OpenAPI (v3) definition.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            OK response.
        """
        with self._raw_client.openapiv3(request_options=request_options) as r:
            yield from r.data


class AsyncUtilitiesV1Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUtilitiesV1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUtilitiesV1Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUtilitiesV1Client
        """
        return self._raw_client

    async def identity(self, *, request_options: typing.Optional[RequestOptions] = None) -> UtilitiesIdentityResultV1:
        """
        Test if your API key is valid, and which roles it has.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UtilitiesIdentityResultV1
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.utilities_v1.identity()


        asyncio.run(main())
        """
        _response = await self._raw_client.identity(request_options=request_options)
        return _response.data

    async def openapi(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.AsyncIterator[bytes]:
        """
        Get the OpenAPI (v2) definition.

        **DEPRECATED**: Please use the OpenAPIV3 endpoint instead. The schema returned from this endpoint does not contain new options and endpoints added in 2025 and later.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK response.
        """
        async with self._raw_client.openapi(request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def openapiv3(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Get the OpenAPI (v3) definition.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            OK response.
        """
        async with self._raw_client.openapiv3(request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
