# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.users_list_result_v2 import UsersListResultV2
from ..types.users_show_result_v2 import UsersShowResultV2
from .raw_client import AsyncRawUsersV2Client, RawUsersV2Client


class UsersV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUsersV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUsersV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUsersV2Client
        """
        return self._raw_client

    def list(
        self,
        *,
        email: typing.Optional[str] = None,
        slack_user_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UsersListResultV2:
        """
        List users in your account.

        Parameters
        ----------
        email : typing.Optional[str]
            Filter by email address

        slack_user_id : typing.Optional[str]
            Filter by Slack user ID

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsersListResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.users_v2.list(
            email="john.doe@incident.io",
            slack_user_id="U12345678",
            page_size=25,
            after="01FDAG4SAP5TYPT98WGR2N7W91",
        )
        """
        _response = self._raw_client.list(
            email=email, slack_user_id=slack_user_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data

    def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> UsersShowResultV2:
        """
        Get a single user.

        Parameters
        ----------
        id : str
            Unique identifier of the user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsersShowResultV2
            OK response.

        Examples
        --------
        from fern import IncidentIO

        client = IncidentIO()
        client.users_v2.show(
            id="01FCNDV6P870EA6S7TK1DSYDG0",
        )
        """
        _response = self._raw_client.show(id, request_options=request_options)
        return _response.data


class AsyncUsersV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUsersV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUsersV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUsersV2Client
        """
        return self._raw_client

    async def list(
        self,
        *,
        email: typing.Optional[str] = None,
        slack_user_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UsersListResultV2:
        """
        List users in your account.

        Parameters
        ----------
        email : typing.Optional[str]
            Filter by email address

        slack_user_id : typing.Optional[str]
            Filter by Slack user ID

        page_size : typing.Optional[int]
            Integer number of records to return

        after : typing.Optional[str]
            An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsersListResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.users_v2.list(
                email="john.doe@incident.io",
                slack_user_id="U12345678",
                page_size=25,
                after="01FDAG4SAP5TYPT98WGR2N7W91",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            email=email, slack_user_id=slack_user_id, page_size=page_size, after=after, request_options=request_options
        )
        return _response.data

    async def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> UsersShowResultV2:
        """
        Get a single user.

        Parameters
        ----------
        id : str
            Unique identifier of the user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsersShowResultV2
            OK response.

        Examples
        --------
        import asyncio

        from fern import AsyncIncidentIO

        client = AsyncIncidentIO()


        async def main() -> None:
            await client.users_v2.show(
                id="01FCNDV6P870EA6S7TK1DSYDG0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.show(id, request_options=request_options)
        return _response.data
