# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .action_v1status import ActionV1Status
from .external_issue_reference_v1 import ExternalIssueReferenceV1
from .user_v1 import UserV1


class ActionV1(UniversalBaseModel):
    assignee: typing.Optional[UserV1] = None
    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the action was completed
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the action was created
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the action
    """

    external_issue_reference: typing.Optional[ExternalIssueReferenceV1] = None
    follow_up: bool = pydantic.Field()
    """
    Whether an action is marked as follow-up
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the action
    """

    incident_id: str = pydantic.Field()
    """
    Unique identifier of the incident the action belongs to
    """

    status: ActionV1Status = pydantic.Field()
    """
    Status of the action
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the action was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
