# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alert_actor_v2 import AlertActorV2
from .api_key_v2 import ApiKeyV2
from .user_v2 import UserV2
from .workflow_actor_v2 import WorkflowActorV2


class ActorV2(UniversalBaseModel):
    alert: typing.Optional[AlertActorV2] = None
    api_key: typing.Optional[ApiKeyV2] = None
    user: typing.Optional[UserV2] = None
    workflow: typing.Optional[WorkflowActorV2] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
