# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alert_route_auto_generated_template_binding_payload_v2 import AlertRouteAutoGeneratedTemplateBindingPayloadV2
from .alert_route_custom_field_binding_payload_v2 import AlertRouteCustomFieldBindingPayloadV2
from .alert_route_severity_binding_payload_v2 import AlertRouteSeverityBindingPayloadV2
from .alert_route_template_binding_payload_v2 import AlertRouteTemplateBindingPayloadV2


class AlertRouteIncidentTemplatePayloadV2(UniversalBaseModel):
    custom_fields: typing.Optional[typing.List[AlertRouteCustomFieldBindingPayloadV2]] = pydantic.Field(default=None)
    """
    Custom fields configuration
    """

    incident_mode: typing.Optional[AlertRouteTemplateBindingPayloadV2] = None
    incident_type: typing.Optional[AlertRouteTemplateBindingPayloadV2] = None
    name: AlertRouteAutoGeneratedTemplateBindingPayloadV2
    severity: typing.Optional[AlertRouteSeverityBindingPayloadV2] = None
    start_in_triage: typing.Optional[AlertRouteTemplateBindingPayloadV2] = None
    summary: typing.Optional[AlertRouteAutoGeneratedTemplateBindingPayloadV2] = None
    workspace: typing.Optional[AlertRouteTemplateBindingPayloadV2] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
