# This file was auto-generated by Fern from our API Definition.

import typing

AlertRouteCustomFieldBindingV2MergeStrategy = typing.Union[
    typing.Literal["first-wins", "last-wins", "append"], typing.Any
]
