# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AlertAttributeCatalogEntryV2(UniversalBaseModel):
    catalog_type_id: str = pydantic.Field()
    """
    ID of this catalog type
    """

    id: str = pydantic.Field()
    """
    ID of this catalog entry
    """

    name: str = pydantic.Field()
    """
    Name is the human readable name of this entry
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
