# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alert_route_severity_binding_payload_v2merge_strategy import AlertRouteSeverityBindingPayloadV2MergeStrategy
from .engine_param_binding_payload_v2 import EngineParamBindingPayloadV2


class AlertRouteSeverityBindingPayloadV2(UniversalBaseModel):
    binding: typing.Optional[EngineParamBindingPayloadV2] = None
    merge_strategy: AlertRouteSeverityBindingPayloadV2MergeStrategy = pydantic.Field()
    """
    Strategy for merging severity when multiple alerts create/update the same incident
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
