# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audit_log_private_escalation_access_attempted_metadata_v2outcome import (
    AuditLogPrivateEscalationAccessAttemptedMetadataV2Outcome,
)


class AuditLogPrivateEscalationAccessAttemptedMetadataV2(UniversalBaseModel):
    outcome: typing.Optional[AuditLogPrivateEscalationAccessAttemptedMetadataV2Outcome] = pydantic.Field(default=None)
    """
    Whether or not the user was able to access the private escalation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
