# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuditLogScimGroupSeatMappingChangedMetadataV2(UniversalBaseModel):
    after_seat_types: str = pydantic.Field()
    """
    The seat types assigned to this SCIM group after the mapping was changed
    """

    before_seat_types: str = pydantic.Field()
    """
    The seat types assigned to this SCIM group before the mapping was changed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
