# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audit_log_actor_v2 import AuditLogActorV2
from .audit_log_entry_context_v2 import AuditLogEntryContextV2
from .audit_log_target_v2 import AuditLogTargetV2


class AuditLogsApiKeyDeletedV1(UniversalBaseModel):
    action: str = pydantic.Field()
    """
    The type of log entry that this is
    """

    actor: AuditLogActorV2
    context: AuditLogEntryContextV2
    occurred_at: dt.datetime = pydantic.Field()
    """
    When the entry occurred
    """

    targets: typing.List[AuditLogTargetV2] = pydantic.Field()
    """
    The custom field that was created
    """

    version: int = pydantic.Field()
    """
    Which version the event is
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
