# This file was auto-generated by Fern from our API Definition.

import typing

AuditLogActorV2Type = typing.Union[
    typing.Literal["user", "system", "api_key", "workflow", "external_resource"], typing.Any
]
