# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audit_log_actor_metadata_v2 import AuditLogActorMetadataV2
from .audit_log_actor_v2type import AuditLogActorV2Type


class AuditLogActorV2(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the actor
    """

    metadata: typing.Optional[AuditLogActorMetadataV2] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the actor
    """

    type: AuditLogActorV2Type = pydantic.Field()
    """
    The type of actor
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
