# This file was auto-generated by Fern from our API Definition.

import typing

CatalogTypeV3CategoriesItem = typing.Union[
    typing.Literal["customer", "issue-tracker", "product-feature", "service", "on-call", "team", "user"], typing.Any
]
