# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CatalogEntryReferenceV2(UniversalBaseModel):
    archived_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this entry was archived
    """

    catalog_entry_id: str = pydantic.Field()
    """
    ID of this catalog entry
    """

    catalog_entry_name: str = pydantic.Field()
    """
    The name of this entry
    """

    catalog_type_id: str = pydantic.Field()
    """
    ID of this catalog type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
