# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .catalog_type_schema_v2 import CatalogTypeSchemaV2
from .catalog_type_v2categories_item import CatalogTypeV2CategoriesItem
from .catalog_type_v2color import CatalogTypeV2Color
from .catalog_type_v2icon import CatalogTypeV2Icon


class CatalogTypeV2(UniversalBaseModel):
    annotations: typing.Dict[str, str] = pydantic.Field()
    """
    Annotations that can track metadata about this type
    """

    categories: typing.List[CatalogTypeV2CategoriesItem] = pydantic.Field()
    """
    What categories is this type considered part of
    """

    color: CatalogTypeV2Color = pydantic.Field()
    """
    Sets the display color of this type in the dashboard
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When this type was created
    """

    description: str = pydantic.Field()
    """
    Human readble description of this type
    """

    dynamic_resource_parameter: typing.Optional[str] = pydantic.Field(default=None)
    """
    If this is a dynamic catalog type, this will be the unique parameter for identitfying this resource externally.
    """

    estimated_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    If populated, gives an estimated count of entries for this type
    """

    icon: CatalogTypeV2Icon = pydantic.Field()
    """
    Sets the display icon of this type in the dashboard
    """

    id: str = pydantic.Field()
    """
    ID of this catalog type
    """

    is_editable: bool = pydantic.Field()
    """
    Catalog types that are synced with external resources can't be edited
    """

    last_synced_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this type was last synced (if it's ever been sync'd)
    """

    name: str = pydantic.Field()
    """
    Name is the human readable name of this type
    """

    ranked: bool = pydantic.Field()
    """
    If this type should be ranked
    """

    registry_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The registry resource this type is synced from, if any
    """

    required_integrations: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    If populated, the integrations required for this type
    """

    schema_: typing_extensions.Annotated[CatalogTypeSchemaV2, FieldMetadata(alias="schema")] = pydantic.Field(
        alias="schema"
    )
    semantic_type: str = pydantic.Field()
    """
    This type has been deprecated, and will always be empty.
    """

    source_repo_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The url of the external repository where this type is managed
    """

    type_name: str = pydantic.Field()
    """
    The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When this type was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
