# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .condition_operation_v2 import ConditionOperationV2
from .condition_subject_v2 import ConditionSubjectV2
from .engine_param_binding_v2 import EngineParamBindingV2


class ConditionV2(UniversalBaseModel):
    operation: ConditionOperationV2
    param_bindings: typing.List[EngineParamBindingV2] = pydantic.Field()
    """
    Bindings for the operation parameters
    """

    subject: ConditionSubjectV2

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
