# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .custom_field_option_v1 import CustomFieldOptionV1
from .custom_field_type_info_v1field_type import CustomFieldTypeInfoV1FieldType


class CustomFieldTypeInfoV1(UniversalBaseModel):
    description: str = pydantic.Field()
    """
    Description of the custom field
    """

    field_type: CustomFieldTypeInfoV1FieldType = pydantic.Field()
    """
    Type of custom field
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the custom field
    """

    name: str = pydantic.Field()
    """
    Human readable name for the custom field
    """

    options: typing.List[CustomFieldOptionV1] = pydantic.Field()
    """
    What options are available for this custom field, if this field has options
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
