# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .user_v2 import UserV2
from .weekday_interval_config_v2 import WeekdayIntervalConfigV2


class EscalationPathV2(UniversalBaseModel):
    current_responders: typing.Optional[typing.List[UserV2]] = pydantic.Field(default=None)
    """
    Users who are currently on-call for this escalation path
    """

    id: str = pydantic.Field()
    """
    Unique identifier for this escalation path.
    """

    name: str = pydantic.Field()
    """
    The name of this escalation path, for the user's reference.
    """

    path: typing.List["EscalationPathNodeV2"] = pydantic.Field()
    """
    The nodes that form the levels and branches of this escalation path.
    """

    team_ids: typing.List[str] = pydantic.Field()
    """
    IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
    """

    working_hours: typing.Optional[typing.List[WeekdayIntervalConfigV2]] = pydantic.Field(default=None)
    """
    The working hours for this escalation path.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .escalation_path_node_if_else_v2 import EscalationPathNodeIfElseV2  # noqa: E402, I001
from .escalation_path_node_v2 import EscalationPathNodeV2  # noqa: E402, I001

update_forward_refs(
    EscalationPathV2, EscalationPathNodeIfElseV2=EscalationPathNodeIfElseV2, EscalationPathNodeV2=EscalationPathNodeV2
)
