# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .escalation_path_target_v2schedule_mode import EscalationPathTargetV2ScheduleMode
from .escalation_path_target_v2type import EscalationPathTargetV2Type
from .escalation_path_target_v2urgency import EscalationPathTargetV2Urgency


class EscalationPathTargetV2(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Uniquely identifies an entity of this type
    """

    schedule_mode: typing.Optional[EscalationPathTargetV2ScheduleMode] = pydantic.Field(default=None)
    """
    Only set for schedule targets, and either currently_on_call, all_users or all_users_for_rota and specifies which users to fetch from the schedule
    """

    type: EscalationPathTargetV2Type = pydantic.Field()
    """
    Controls what type of entity this target identifies, such as EscalationPolicy or User
    """

    urgency: EscalationPathTargetV2Urgency = pydantic.Field()
    """
    The urgency of this escalation path target
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
