# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EscalationPathRoundRobinConfigV2(UniversalBaseModel):
    enabled: bool = pydantic.Field()
    """
    Whether round robin is enabled for this level
    """

    rotate_after_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    How long should we wait before rotating to the next target in a round robin, if not set will stick with a single target per level.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
