# This file was auto-generated by Fern from our API Definition.

import typing

EscalationPathTargetV2Type = typing.Union[
    typing.Literal["schedule", "user", "slack_channel", "msteams_channel"], typing.Any
]
