# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EscalationPathNodeRepeatV2(UniversalBaseModel):
    repeat_times: int = pydantic.Field()
    """
    How many times to repeat these nodes
    """

    to_node: str = pydantic.Field()
    """
    Which node ID we begin repeating from.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
