# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .condition_group_v2 import ConditionGroupV2


class ExpressionFilterOptsV2(UniversalBaseModel):
    condition_groups: typing.List[ConditionGroupV2] = pydantic.Field()
    """
    The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
