# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .expression_branches_opts_v2 import ExpressionBranchesOptsV2
from .expression_filter_opts_v2 import ExpressionFilterOptsV2
from .expression_navigate_opts_v2 import ExpressionNavigateOptsV2
from .expression_operation_v2operation_type import ExpressionOperationV2OperationType
from .expression_parse_opts_v2 import ExpressionParseOptsV2
from .returns_meta_v2 import ReturnsMetaV2


class ExpressionOperationV2(UniversalBaseModel):
    branches: typing.Optional[ExpressionBranchesOptsV2] = None
    filter: typing.Optional[ExpressionFilterOptsV2] = None
    navigate: typing.Optional[ExpressionNavigateOptsV2] = None
    operation_type: ExpressionOperationV2OperationType = pydantic.Field()
    """
    The type of the operation
    """

    parse: typing.Optional[ExpressionParseOptsV2] = None
    returns: ReturnsMetaV2

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
