# This file was auto-generated by Fern from our API Definition.

import typing

ExpressionOperationPayloadV2OperationType = typing.Union[
    typing.Literal[
        "navigate", "filter", "concatenate", "count", "min", "max", "sum", "random", "first", "parse", "branches"
    ],
    typing.Any,
]
