# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .external_issue_reference_v1provider import ExternalIssueReferenceV1Provider


class ExternalIssueReferenceV1(UniversalBaseModel):
    issue_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human readable ID for the issue
    """

    issue_permalink: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL linking directly to the action in the issue tracker
    """

    provider: typing.Optional[ExternalIssueReferenceV1Provider] = pydantic.Field(default=None)
    """
    ID of the issue tracker provider
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
