# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_v2 import ActorV2
from .external_issue_reference_v2 import ExternalIssueReferenceV2
from .follow_up_priority_v2 import FollowUpPriorityV2
from .follow_up_v2status import FollowUpV2Status
from .user_v2 import UserV2


class FollowUpV2(UniversalBaseModel):
    assignee: typing.Optional[UserV2] = None
    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the follow-up was completed
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the follow-up was created
    """

    creator: ActorV2
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the follow-up
    """

    external_issue_reference: typing.Optional[ExternalIssueReferenceV2] = None
    id: str = pydantic.Field()
    """
    Unique identifier for the follow-up
    """

    incident_id: str = pydantic.Field()
    """
    Unique identifier of the incident the follow-up belongs to
    """

    labels: typing.List[str] = pydantic.Field()
    """
    Labels associated with this follow-up
    """

    priority: typing.Optional[FollowUpPriorityV2] = None
    status: FollowUpV2Status = pydantic.Field()
    """
    Status of the follow-up
    """

    title: str = pydantic.Field()
    """
    Title of the follow-up
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the follow-up was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
