# This file was auto-generated by Fern from our API Definition.

import typing

IdentityV1RolesItem = typing.Union[
    typing.Literal[
        "viewer",
        "incident_creator",
        "incident_editor",
        "manage_settings",
        "global_access",
        "catalog_viewer",
        "catalog_editor",
        "incident_memberships_editor",
        "schedules_editor",
        "schedules_reader",
        "schedule_overrides_editor",
        "workflows_editor",
        "private_workflows_editor",
        "on_call_editor",
        "escalation_creator",
        "post_incident_flow_opt_out",
        "security_settings_editor",
        "investigation_download",
        "team_memberships_manage",
    ],
    typing.Any,
]
