# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alert_slim_v2 import AlertSlimV2
from .incident_slim_v2 import IncidentSlimV2


class IncidentAlertV2(UniversalBaseModel):
    alert: AlertSlimV2
    alert_route_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the alert route that created this incident alert
    """

    id: str = pydantic.Field()
    """
    The ID of this alert
    """

    incident: IncidentSlimV2

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
