# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .incident_role_v1role_type import IncidentRoleV1RoleType


class IncidentRoleV1(UniversalBaseModel):
    created_at: dt.datetime = pydantic.Field()
    """
    When the role was created
    """

    description: str = pydantic.Field()
    """
    Describes the purpose of the role
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the role
    """

    instructions: str = pydantic.Field()
    """
    Provided to whoever is nominated for the role. Note that this will be empty for the 'reporter' role.
    """

    name: str = pydantic.Field()
    """
    Human readable name of the incident role
    """

    required: typing.Optional[bool] = pydantic.Field(default=None)
    """
    DEPRECATED: this will always be false.
    """

    role_type: IncidentRoleV1RoleType = pydantic.Field()
    """
    Type of incident role
    """

    shortform: str = pydantic.Field()
    """
    Short human readable name for Slack. Note that this will be empty for the 'reporter' role.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the role was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
