# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .incident_slim_v2status_category import IncidentSlimV2StatusCategory
from .incident_slim_v2visibility import IncidentSlimV2Visibility


class IncidentSlimV2(UniversalBaseModel):
    """
    Incident slim is a subset of the full incident object, listing key fields.
    """

    external_id: int = pydantic.Field()
    """
    External identifier for the incident - often displayed with an INC- prefix
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the incident
    """

    name: str = pydantic.Field()
    """
    Explanation of the incident
    """

    reference: str = pydantic.Field()
    """
    Reference to this incident, as displayed across the product
    """

    status_category: IncidentSlimV2StatusCategory = pydantic.Field()
    """
    The category of the incidents status
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detailed description of the incident
    """

    visibility: IncidentSlimV2Visibility = pydantic.Field()
    """
    Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
