# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .incident_duration_metric_v2 import IncidentDurationMetricV2


class IncidentDurationMetricWithValueV2(UniversalBaseModel):
    duration_metric: IncidentDurationMetricV2
    value_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    The calculated durations for this metric
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
