# This file was auto-generated by Fern from our API Definition.

import typing

IncidentStatusV2Category = typing.Union[
    typing.Literal["triage", "declined", "merged", "canceled", "live", "learning", "closed", "paused"], typing.Any
]
