# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .external_resource_v1 import ExternalResourceV1


class IncidentAttachmentV1(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of this incident membership
    """

    incident_id: str = pydantic.Field()
    """
    Unique identifier of the incident
    """

    resource: ExternalResourceV1

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
