# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .catalog_engine_param_binding_payload_v3 import CatalogEngineParamBindingPayloadV3


class PartialEntryPayloadV3(UniversalBaseModel):
    """
    Represents a partial entry update, allowing selective field updates
    """

    aliases: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    If specified, will update the aliases of the entry. When omitted, preserves the existing aliases.
    """

    attribute_values: typing.Dict[str, CatalogEngineParamBindingPayloadV3] = pydantic.Field()
    """
    The attribute values to apply to this entry
    """

    entry_id: str = pydantic.Field()
    """
    ID of the relevant catalog entry
    """

    external_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    If specified, will update the external ID of the entry. When omitted, preserves the existing external ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    If specified, will update the name of the entry. When omitted, preserves the existing name.
    """

    rank: typing.Optional[int] = pydantic.Field(default=None)
    """
    If specified, will update the rank of the entry. When omitted, rank will be set to null (allowing rank removal).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
