# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ScheduleHolidaysPublicConfigPayloadV2(UniversalBaseModel):
    country_codes: typing.List[str] = pydantic.Field()
    """
    ISO 3166-1 alpha-2 country codes for the countries that this schedule is configured to view holidays for
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
