# This file was auto-generated by Fern from our API Definition.

import typing

ScheduleRotationWorkingIntervalCreatePayloadV2Weekday = typing.Union[
    typing.Literal["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"], typing.Any
]
