# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .schedule_layer_v2 import ScheduleLayerV2
from .schedule_rotation_handover_v2 import ScheduleRotationHandoverV2
from .schedule_rotation_v2scheduling_mode import ScheduleRotationV2SchedulingMode
from .schedule_rotation_working_interval_v2 import ScheduleRotationWorkingIntervalV2
from .user_v2 import UserV2


class ScheduleRotationV2(UniversalBaseModel):
    effective_from: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this rotation config will be effective from
    """

    handover_start_at: dt.datetime = pydantic.Field()
    """
    Defines the next moment we'll trigger a handover
    """

    handovers: typing.List[ScheduleRotationHandoverV2] = pydantic.Field()
    """
    Defines the handover intervals for this rota, in order they should apply
    """

    id: str = pydantic.Field()
    """
    Unique internal ID of the rotation
    """

    layers: typing.List[ScheduleLayerV2] = pydantic.Field()
    """
    Controls how many people are on-call concurrently
    """

    name: str = pydantic.Field()
    """
    Human readable name synced from external provider
    """

    scheduling_mode: typing.Optional[ScheduleRotationV2SchedulingMode] = pydantic.Field(default=None)
    """
    Scheduling algorithm to use for this rotation. 'fair' balances workload by considering handover duration, while 'sequential' uses simple round-robin rotation through users. Only applies when you have asymmetric handovers (e.g., 2 days then 5 days).
    """

    users: typing.List[UserV2] = pydantic.Field()
    """
    Users who are available to be scheduled on this rota
    """

    working_interval: typing.Optional[typing.List[ScheduleRotationWorkingIntervalV2]] = pydantic.Field(default=None)
    """
    DEPRECATED: Use working_intervals instead.
    """

    working_intervals: typing.List[ScheduleRotationWorkingIntervalV2] = pydantic.Field()
    """
    Optional restrictions that define when to schedule people for this rota
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
