# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .schedule_config_create_payload_v2 import ScheduleConfigCreatePayloadV2
from .schedule_holidays_public_config_payload_v2 import ScheduleHolidaysPublicConfigPayloadV2


class ScheduleCreatePayloadV2(UniversalBaseModel):
    annotations: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Annotations that can track metadata about the schedule
    """

    config: typing.Optional[ScheduleConfigCreatePayloadV2] = None
    holidays_public_config: typing.Optional[ScheduleHolidaysPublicConfigPayloadV2] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the schedule
    """

    team_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    IDs of teams that own this schedule
    """

    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timezone of the schedule
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
