# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SeverityV2(UniversalBaseModel):
    created_at: dt.datetime = pydantic.Field()
    """
    When the action was created
    """

    description: str = pydantic.Field()
    """
    Description of the severity
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the severity
    """

    name: str = pydantic.Field()
    """
    Human readable name of the severity
    """

    rank: int = pydantic.Field()
    """
    Rank to help sort severities (lower numbers are less severe)
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the action was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
