# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_v1role import UserV1Role


class UserV1(UniversalBaseModel):
    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address of the user.
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the user
    """

    name: str = pydantic.Field()
    """
    Name of the user
    """

    role: UserV1Role = pydantic.Field()
    """
    DEPRECATED: Role of the user as of March 9th 2023, this value is no longer updated.
    """

    slack_user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slack ID of the user
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
