# This file was auto-generated by Fern from our API Definition.

import typing

WebhooksPrivateIncidentActionCreatedV1ResponseBodyEventType = typing.Union[
    typing.Literal[
        "public_incident.incident_created_v2",
        "private_incident.incident_created_v2",
        "public_incident.incident_updated_v2",
        "private_incident.incident_updated_v2",
        "public_incident.incident_status_updated_v2",
        "public_incident.follow_up_created_v1",
        "private_incident.follow_up_created_v1",
        "public_incident.follow_up_updated_v1",
        "private_incident.follow_up_updated_v1",
        "public_incident.follow_up_created_v2",
        "private_incident.follow_up_created_v2",
        "public_incident.follow_up_updated_v2",
        "private_incident.follow_up_updated_v2",
        "public_incident.action_created_v1",
        "private_incident.action_created_v1",
        "public_incident.action_updated_v1",
        "private_incident.action_updated_v1",
        "public_alert.alert_created_v1",
        "private_alert.alert_created_v1",
        "private_incident.membership_granted_v1",
        "private_incident.membership_revoked_v1",
    ],
    typing.Any,
]
