# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_private_resource_v2 import WebhookPrivateResourceV2
from .webhooks_private_incident_incident_created_v2response_body_event_type import (
    WebhooksPrivateIncidentIncidentCreatedV2ResponseBodyEventType,
)


class WebhooksPrivateIncidentIncidentCreatedV2ResponseBody(UniversalBaseModel):
    event_type: WebhooksPrivateIncidentIncidentCreatedV2ResponseBodyEventType = pydantic.Field()
    """
    What type of event is this webhook for?
    """

    private_incident_incident_created_v2: typing_extensions.Annotated[
        WebhookPrivateResourceV2, FieldMetadata(alias="private_incident.incident_created_v2")
    ] = pydantic.Field(alias="private_incident.incident_created_v2")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
