# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_incident_user_v2 import WebhookIncidentUserV2
from .webhooks_private_incident_membership_revoked_v1response_body_event_type import (
    WebhooksPrivateIncidentMembershipRevokedV1ResponseBodyEventType,
)


class WebhooksPrivateIncidentMembershipRevokedV1ResponseBody(UniversalBaseModel):
    event_type: WebhooksPrivateIncidentMembershipRevokedV1ResponseBodyEventType = pydantic.Field()
    """
    What type of event is this webhook for?
    """

    private_incident_membership_revoked_v1: typing_extensions.Annotated[
        WebhookIncidentUserV2, FieldMetadata(alias="private_incident.membership_revoked_v1")
    ] = pydantic.Field(alias="private_incident.membership_revoked_v1")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
