# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .condition_group_v2 import ConditionGroupV2
from .engine_reference_v2 import EngineReferenceV2
from .expression_v2 import ExpressionV2
from .step_config_slim_v2 import StepConfigSlimV2
from .trigger_slim_v2 import TriggerSlimV2
from .workflow_delay_v2 import WorkflowDelayV2
from .workflow_slim_v2runs_on_incident_modes_item import WorkflowSlimV2RunsOnIncidentModesItem
from .workflow_slim_v2runs_on_incidents import WorkflowSlimV2RunsOnIncidents
from .workflow_slim_v2state import WorkflowSlimV2State


class WorkflowSlimV2(UniversalBaseModel):
    condition_groups: typing.List[ConditionGroupV2] = pydantic.Field()
    """
    Conditions that apply to the workflow trigger
    """

    continue_on_step_error: bool = pydantic.Field()
    """
    Whether to continue executing the workflow if a step fails
    """

    delay: typing.Optional[WorkflowDelayV2] = None
    expressions: typing.List[ExpressionV2] = pydantic.Field()
    """
    Expressions that make variables available in the scope
    """

    folder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Folder to display the workflow in
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the workflow
    """

    include_private_escalations: bool = pydantic.Field()
    """
    Whether to include private escalations
    """

    include_private_incidents: bool = pydantic.Field()
    """
    Whether to include private incidents
    """

    name: str = pydantic.Field()
    """
    Name provided by the user when creating the workflow
    """

    once_for: typing.List[EngineReferenceV2] = pydantic.Field()
    """
    This workflow will run 'once for' a list of references
    """

    runs_from: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The time from which this workflow will run on incidents
    """

    runs_on_incident_modes: typing.List[WorkflowSlimV2RunsOnIncidentModesItem] = pydantic.Field()
    """
    Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
    """

    runs_on_incidents: WorkflowSlimV2RunsOnIncidents = pydantic.Field()
    """
    Which incidents should the workflow be applied to?
    """

    shortform: typing.Optional[str] = pydantic.Field(default=None)
    """
    The shortform used to trigger this workflow (only applicable for manual triggers)
    """

    state: WorkflowSlimV2State = pydantic.Field()
    """
    What state this workflow is in
    """

    steps: typing.List[StepConfigSlimV2] = pydantic.Field()
    """
    Steps that are executed as part of the workflow
    """

    trigger: TriggerSlimV2
    version: int = pydantic.Field()
    """
    Revision of the workflow, uniquely identifying it's version
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
