# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.custom_field_filter_by_options_v2 import CustomFieldFilterByOptionsV2
from ..types.custom_fields_create_result_v2 import CustomFieldsCreateResultV2
from ..types.custom_fields_list_result_v2 import CustomFieldsListResultV2
from ..types.custom_fields_show_result_v2 import CustomFieldsShowResultV2
from ..types.custom_fields_update_result_v2 import CustomFieldsUpdateResultV2
from .types.custom_fields_create_payload_v2field_type import CustomFieldsCreatePayloadV2FieldType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCustomFieldsV2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CustomFieldsListResultV2]:
        """
        List all custom fields for an organisation.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CustomFieldsListResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/custom_fields",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsListResultV2,
                    parse_obj_as(
                        type_=CustomFieldsListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        description: str,
        field_type: CustomFieldsCreatePayloadV2FieldType,
        name: str,
        catalog_type_id: typing.Optional[str] = OMIT,
        filter_by: typing.Optional[CustomFieldFilterByOptionsV2] = OMIT,
        group_by_catalog_attribute_id: typing.Optional[str] = OMIT,
        helptext_catalog_attribute_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CustomFieldsCreateResultV2]:
        """
        Create a new custom field

        Parameters
        ----------
        description : str
            Description of the custom field

        field_type : CustomFieldsCreatePayloadV2FieldType
            Type of custom field

        name : str
            Human readable name for the custom field

        catalog_type_id : typing.Optional[str]
            For catalog fields, the ID of the associated catalog type

        filter_by : typing.Optional[CustomFieldFilterByOptionsV2]

        group_by_catalog_attribute_id : typing.Optional[str]
            For catalog fields, the ID of the attribute used to group catalog entries (if applicable)

        helptext_catalog_attribute_id : typing.Optional[str]
            Which catalog attribute provides helptext for the options

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CustomFieldsCreateResultV2]
            Created response.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/custom_fields",
            method="POST",
            json={
                "catalog_type_id": catalog_type_id,
                "description": description,
                "field_type": field_type,
                "filter_by": convert_and_respect_annotation_metadata(
                    object_=filter_by, annotation=CustomFieldFilterByOptionsV2, direction="write"
                ),
                "group_by_catalog_attribute_id": group_by_catalog_attribute_id,
                "helptext_catalog_attribute_id": helptext_catalog_attribute_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsCreateResultV2,
                    parse_obj_as(
                        type_=CustomFieldsCreateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CustomFieldsShowResultV2]:
        """
        Get a single custom field.

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CustomFieldsShowResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsShowResultV2,
                    parse_obj_as(
                        type_=CustomFieldsShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: str,
        *,
        description: str,
        name: str,
        filter_by: typing.Optional[CustomFieldFilterByOptionsV2] = OMIT,
        group_by_catalog_attribute_id: typing.Optional[str] = OMIT,
        helptext_catalog_attribute_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CustomFieldsUpdateResultV2]:
        """
        Update the details of a custom field

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        description : str
            Description of the custom field

        name : str
            Human readable name for the custom field

        filter_by : typing.Optional[CustomFieldFilterByOptionsV2]

        group_by_catalog_attribute_id : typing.Optional[str]
            For catalog fields, the ID of the attribute used to group catalog entries (if applicable)

        helptext_catalog_attribute_id : typing.Optional[str]
            Which catalog attribute provides helptext for the options

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CustomFieldsUpdateResultV2]
            OK response.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "description": description,
                "filter_by": convert_and_respect_annotation_metadata(
                    object_=filter_by, annotation=CustomFieldFilterByOptionsV2, direction="write"
                ),
                "group_by_catalog_attribute_id": group_by_catalog_attribute_id,
                "helptext_catalog_attribute_id": helptext_catalog_attribute_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsUpdateResultV2,
                    parse_obj_as(
                        type_=CustomFieldsUpdateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Delete a custom field

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCustomFieldsV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CustomFieldsListResultV2]:
        """
        List all custom fields for an organisation.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CustomFieldsListResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/custom_fields",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsListResultV2,
                    parse_obj_as(
                        type_=CustomFieldsListResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        description: str,
        field_type: CustomFieldsCreatePayloadV2FieldType,
        name: str,
        catalog_type_id: typing.Optional[str] = OMIT,
        filter_by: typing.Optional[CustomFieldFilterByOptionsV2] = OMIT,
        group_by_catalog_attribute_id: typing.Optional[str] = OMIT,
        helptext_catalog_attribute_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CustomFieldsCreateResultV2]:
        """
        Create a new custom field

        Parameters
        ----------
        description : str
            Description of the custom field

        field_type : CustomFieldsCreatePayloadV2FieldType
            Type of custom field

        name : str
            Human readable name for the custom field

        catalog_type_id : typing.Optional[str]
            For catalog fields, the ID of the associated catalog type

        filter_by : typing.Optional[CustomFieldFilterByOptionsV2]

        group_by_catalog_attribute_id : typing.Optional[str]
            For catalog fields, the ID of the attribute used to group catalog entries (if applicable)

        helptext_catalog_attribute_id : typing.Optional[str]
            Which catalog attribute provides helptext for the options

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CustomFieldsCreateResultV2]
            Created response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/custom_fields",
            method="POST",
            json={
                "catalog_type_id": catalog_type_id,
                "description": description,
                "field_type": field_type,
                "filter_by": convert_and_respect_annotation_metadata(
                    object_=filter_by, annotation=CustomFieldFilterByOptionsV2, direction="write"
                ),
                "group_by_catalog_attribute_id": group_by_catalog_attribute_id,
                "helptext_catalog_attribute_id": helptext_catalog_attribute_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsCreateResultV2,
                    parse_obj_as(
                        type_=CustomFieldsCreateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CustomFieldsShowResultV2]:
        """
        Get a single custom field.

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CustomFieldsShowResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsShowResultV2,
                    parse_obj_as(
                        type_=CustomFieldsShowResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: str,
        *,
        description: str,
        name: str,
        filter_by: typing.Optional[CustomFieldFilterByOptionsV2] = OMIT,
        group_by_catalog_attribute_id: typing.Optional[str] = OMIT,
        helptext_catalog_attribute_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CustomFieldsUpdateResultV2]:
        """
        Update the details of a custom field

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        description : str
            Description of the custom field

        name : str
            Human readable name for the custom field

        filter_by : typing.Optional[CustomFieldFilterByOptionsV2]

        group_by_catalog_attribute_id : typing.Optional[str]
            For catalog fields, the ID of the attribute used to group catalog entries (if applicable)

        helptext_catalog_attribute_id : typing.Optional[str]
            Which catalog attribute provides helptext for the options

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CustomFieldsUpdateResultV2]
            OK response.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "description": description,
                "filter_by": convert_and_respect_annotation_metadata(
                    object_=filter_by, annotation=CustomFieldFilterByOptionsV2, direction="write"
                ),
                "group_by_catalog_attribute_id": group_by_catalog_attribute_id,
                "helptext_catalog_attribute_id": helptext_catalog_attribute_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CustomFieldsUpdateResultV2,
                    parse_obj_as(
                        type_=CustomFieldsUpdateResultV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Delete a custom field

        Parameters
        ----------
        id : str
            Unique identifier for the custom field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/custom_fields/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
